In [1]:
library(plyr)
library(dplyr)
library(tidyr)
library(lme4)
library(lmerTest)
library(interactions)
library(ggplot2)
library(emmeans)
library(rempsyc)

Attaching package: 'dplyr'


The following objects are masked from 'package:plyr':

    arrange, count, desc, failwith, id, mutate, rename, summarise,
    summarize


The following objects are masked from 'package:stats':

    filter, lag


The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union


Loading required package: Matrix


Attaching package: 'Matrix'


The following objects are masked from 'package:tidyr':

    expand, pack, unpack



Attaching package: 'lmerTest'


The following object is masked from 'package:lme4':

    lmer


The following object is masked from 'package:stats':

    step


Welcome to emmeans.
Caution: You lose important information if you filter this package's results.
See '? untidy'

Suggested APA citation: Th<U+00E9>riault, R. (2023). rempsyc: Convenience functions for psychology.
Journal of Open Source Software, 8(87), 5466. https://doi.org/10.21105/joss.05466

# TF measures predicted by acc * soc * age

## Load data

In [2]:
rm(list = ls())
session = "s1_r1"
analysis_path = "/home/data/NDClab/analyses/thrive-theta-ddm/"
source(sprintf("%s/code/statistics/lmer_export_apa.R", analysis_path))
source(sprintf("%s/code/statistics/find_newest_file.R", analysis_path))
pic_path <- (sprintf("%s/derivatives/figs/%s", analysis_path, session))
# tf_data <- read.csv("/Users/fzaki001/IDENTIFIABLE/tf_data_collapsed_merged.csv")
tf_data <- read.csv(find_newest_file(sprintf("%s/derivatives/csv/%s/thrive*long*.csv", analysis_path, session)))
table_output_path = sprintf("%s/derivatives/statistics/full_sample/", analysis_path)

id_cols <- c('sub', 'age_m', 'sex', 'acc', 'soc', 'dp_inperson', 'first_soc')
data_cols <- c(
    'power_early',
    'ITPS_early',
    'ICPS_early_DLPFC_collapsed',
    'ICPS_early_MOTOR_collapsed',
    'ICPS_early_OCC_collapsed'
)
tf_data <- tf_data[, c(id_cols, data_cols)]
tf_data <- tf_data %>%
  filter(!if_all(c(data_cols), is.na))

tf_data$soc <- as.factor(tf_data$soc)
tf_data$sub <- as.factor(tf_data$sub)
tf_data$sex <- as.factor(tf_data$sex)
tf_data$acc <- as.factor(tf_data$acc)
tf_data$first_soc <- as.factor(tf_data$first_soc)
# tf_data$task_num <- as.factor(tf_data$task_num)
tf_data$dp_inperson <- as.factor(tf_data$dp_inperson)

tf_data[c("age_m", data_cols)] <- as.data.frame(scale(tf_data[c("age_m", data_cols)]))

tf_data$soc <- revalue(tf_data$soc, c("0" = "NS", "1" = "S"))
tf_data$sex <- revalue(tf_data$sex, c("1" = "M", "2" = "F"))
tf_data$acc <- revalue(tf_data$acc, c("0" = "Error", "1" = "Correct"))

contrasts(tf_data$soc) <- rev(contr.sum(2))
contrasts(tf_data$acc) <- rev(contr.sum(2))
contrasts(tf_data$first_soc) <- rev(contr.sum(2))
contrasts(tf_data$sex) <- rev(contr.sum(2))
# contrasts(tf_data$task_num) <- rev(contr.sum(2))
contrasts(tf_data$dp_inperson) <- rev(contr.sum(2))

[1] "The newest file is: /home/data/NDClab/analyses/thrive-theta-ddm//derivatives/csv/s1_r1/thrive_long_s1_r1_22_02_2026_23_31_39.csv"

Warning message:
"There was 1 warning in `filter()`.
i In argument: `!if_all(c(data_cols), is.na)`.
Caused by warning:
! Using an external vector in selections was deprecated in tidyselect 1.1.0.
i Please use `all_of()` or `any_of()` instead.
  # Was:
  data %>% select(data_cols)

  # Now:
  data %>% select(all_of(data_cols))

See <https://tidyselect.r-lib.org/reference/faq-external-vector.html>."

## Power

In [16]:
label <- "power"
model <- lmer(power_early ~ acc * age_m * soc + sex + dp_inperson + (1 | sub),
              data = tf_data)
summary(model)
# lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: power_early ~ acc * age_m * soc + sex + dp_inperson + (1 | sub)
   Data: tf_data

REML criterion at convergence: 1590.4

Scaled residuals:
    Min      1Q  Median      3Q     Max
-2.7967 -0.5339 -0.0085  0.5582  3.8812

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.1479   0.3846
 Residual             0.2633   0.5132
Number of obs: 855, groups:  sub, 233

Fixed effects:
                  Estimate Std. Error         df t value Pr(>|t|)
(Intercept)       0.015636   0.044918 226.874565   0.348 0.728087
acc1             -0.735354   0.017600 623.311749 -41.780  < 2e-16 ***
age_m             0.167464   0.030969 228.434590   5.407 1.61e-07 ***
soc1              0.013577   0.017903 653.072684   0.758 0.448495
sex1             -0.119092   0.030985 226.577448  -3.844 0.000158 ***
dp_inperson1     -0.004465   0.044967 226.122430  -0.099 0.920986
acc1:age_m       -0.088455   0.017627 623.307814  -5.018 6.81e-07 ***
acc1:soc1        -0.010976   0.017590 622.262477  -0.624 0.532856
age_m:soc1        0.002858   0.017967 656.832544   0.159 0.873683
acc1:age_m:soc1   0.019506   0.017619 622.526129   1.107 0.268686
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
            (Intr) acc1   age_m  soc1   sex1   dp_np1 acc1:_ acc1:1 ag_m:1
acc1        -0.004
age_m        0.047 -0.004
soc1        -0.015  0.000  0.025
sex1        -0.013 -0.004  0.018  0.003
dp_inpersn1 -0.724 -0.003 -0.065  0.012 -0.034
acc1:age_m  -0.002  0.003 -0.013  0.001 -0.001 -0.001
acc1:soc1    0.001 -0.011  0.001 -0.010  0.003  0.000  0.030
age_m:soc1   0.027  0.001 -0.001 -0.003  0.005 -0.013 -0.006 -0.006
acc1:g_m:s1  0.000  0.030 -0.001 -0.006  0.003  0.001 -0.001  0.002 -0.018

In [17]:
# test(emtrends(model, pairwise ~ acc | age_m, var="age_m"), adjust="fdr")
# confint(emtrends(model, pairwise ~ acc | age_m, var="age_m"), adjust="fdr")

simple_slopes <- emtrends(model, ~ acc, var = "age_m")

# View the slopes and significance tests (slope != 0)
summary(simple_slopes, infer = c(TRUE, TRUE),
        adjust='fdr',
       )

library(broom)
library(knitr)

# tidy() converts the object into a clean tibble
tidy_slopes <- tidy(simple_slopes, conf.int = TRUE)

kable(tidy_slopes, digits = 3, format = "simple")

Cannot use mode = "kenward-roger" because *pbkrtest* package is not installed

NOTE: Results may be misleading due to involvement in interactions

  acc     age_m.trend SE         df       lower.CL      upper.CL  t.ratio
1 Error   0.2559193   0.03584042 389.5641  0.1752747652 0.3365638 7.140521
2 Correct 0.0790088   0.03542712 378.9318 -0.0007144323 0.1587320 2.230179
  p.value
1 9.179542e-12
2 2.632066e-02

acc        age_m.trend   std.error        df   conf.low   conf.high   statistic   p.value
--------  ------------  ----------  --------  ---------  ----------  ----------  --------
Error            0.256       0.036   389.564      0.185       0.326       7.141     0.000
Correct          0.079       0.035   378.932      0.009       0.149       2.230     0.026

### Plot

In [56]:
# test(emtrends(model, pairwise ~ acc | age_m, var="age_m"), adjust="fdr")
# confint(emtrends(model, pairwise ~ acc | age_m, var="age_m"), adjust="fdr")

y_label = "Power"
x_label = "Age"

png(file=sprintf("%s/%s_stats.png", pic_path, label), width=8, height=5, units="in", res=600)
interact_plot(model,
              pred = "age_m",
              modx = "acc",
              interval = 1,
              y.label = y_label,
              x.label = x_label,
              legend.main = "Accuracy",
              colors = c("red", "blue"),
              plot.points = T) +
# scale_color_manual(values = c("Error" = "red", "Correct" = "blue")) +
# scale_fill_manual(values = c("Error" = "red", "Correct" = "blue")) +
theme_minimal() +  scale_y_continuous(breaks = seq(-3, 4, by = 1)) +
  scale_x_continuous(breaks = seq(-3, 3, by = 1)) +
theme(
  text = element_text(size = 14),                              # Change the base font size
  axis.title = element_text(size = 16),                        # Change the axis title font size
  axis.text = element_text(size = 14),                         # Change the axis text font size
  legend.text = element_text(size = 14),                       # Change the legend text font size
  legend.title = element_text(size = 14),                     # Change the legend title font size
  plot.title = element_text(size = 18, face = "bold")          # Change the plot title font size and make it bold
)
dev.off()

agg_record_561350890
                   2

## ITPS

In [18]:
label <- "ITPS"
model <- lmer(ITPS_early ~ acc * age_m * soc + sex + dp_inperson + (1 | sub),
              data = tf_data)
summary(model)
# lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: ITPS_early ~ acc * age_m * soc + sex + dp_inperson + (1 | sub)
   Data: tf_data

REML criterion at convergence: 2349.8

Scaled residuals:
    Min      1Q  Median      3Q     Max
-3.4948 -0.5754 -0.0713  0.4674  3.7266

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.2141   0.4627
 Residual             0.7261   0.8521
Number of obs: 851, groups:  sub, 233

Fixed effects:
                  Estimate Std. Error         df t value Pr(>|t|)
(Intercept)      -0.005852   0.061651 221.685804  -0.095 0.924460
acc1             -0.184800   0.029284 617.888980  -6.311  5.3e-10 ***
age_m             0.146848   0.042514 222.799071   3.454 0.000661 ***
soc1              0.004613   0.029651 655.266865   0.156 0.876414
sex1              0.087107   0.042478 220.413373   2.051 0.041486 *
dp_inperson1      0.002897   0.061689 220.827605   0.047 0.962588
acc1:age_m       -0.108977   0.029331 617.628122  -3.715 0.000221 ***
acc1:soc1         0.019690   0.029271 616.581160   0.673 0.501402
age_m:soc1       -0.007901   0.029754 661.183655  -0.266 0.790659
acc1:age_m:soc1   0.010636   0.029321 616.609529   0.363 0.716913
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
            (Intr) acc1   age_m  soc1   sex1   dp_np1 acc1:_ acc1:1 ag_m:1
acc1        -0.005
age_m        0.048 -0.006
soc1        -0.019  0.006  0.030
sex1        -0.017 -0.002  0.015  0.004
dp_inpersn1 -0.725  0.000 -0.064  0.015 -0.026
acc1:age_m  -0.006  0.006 -0.010  0.003 -0.001  0.002
acc1:soc1    0.004 -0.014  0.003 -0.007  0.000 -0.001  0.032
age_m:soc1   0.028  0.003 -0.004  0.003  0.003 -0.009  0.001 -0.009
acc1:g_m:s1  0.004  0.032  0.002 -0.009  0.003 -0.003 -0.007  0.005 -0.011

In [19]:
# test(emtrends(model, pairwise ~ acc | age_m, var="age_m"), adjust="fdr")
# confint(emtrends(model, pairwise ~ acc | age_m, var="age_m"), adjust="fdr")

simple_slopes <- emtrends(model, ~ acc, var = "age_m")

# View the slopes and significance tests (slope != 0)
summary(simple_slopes, infer = c(TRUE, TRUE),
        adjust='fdr',
       )

library(broom)
library(knitr)

# tidy() converts the object into a clean tibble
tidy_slopes <- tidy(simple_slopes, conf.int = TRUE)

kable(tidy_slopes, digits = 3, format = "simple")

Cannot use mode = "kenward-roger" because *pbkrtest* package is not installed

NOTE: Results may be misleading due to involvement in interactions

  acc     age_m.trend SE         df       lower.CL    upper.CL  t.ratio
1 Error   0.25582531  0.05190172 452.2180  0.13910400 0.3725466 4.9290332
2 Correct 0.03787141  0.05139765 445.4925 -0.07772214 0.1534650 0.7368314
  p.value
1 2.323960e-06
2 4.616127e-01

acc        age_m.trend   std.error        df   conf.low   conf.high   statistic   p.value
--------  ------------  ----------  --------  ---------  ----------  ----------  --------
Error            0.256       0.052   452.218      0.154       0.358       4.929     0.000
Correct          0.038       0.051   445.493     -0.063       0.139       0.737     0.462

### Plot

In [19]:
# test(emtrends(model, pairwise ~ acc | age_m, var="age_m"), adjust="fdr")
# confint(emtrends(model, pairwise ~ acc | age_m, var="age_m"), adjust="fdr")

y_label = "ITPS"
x_label = "Age"

png(file=sprintf("%s/%s_stats.png", pic_path, label), width=8, height=5, units="in", res=600)
interact_plot(model,
              pred = "age_m",
              modx = "acc",
              interval = 1,
              y.label = y_label,
              x.label = x_label,
              legend.main = "Accuracy",
              colors = c("red", "blue"),
              plot.points = T) +
# scale_color_manual(values = c("Error" = "red", "Correct" = "blue")) +
# scale_fill_manual(values = c("Error" = "red", "Correct" = "blue")) +
theme_minimal() +  scale_y_continuous(breaks = seq(-3, 4, by = 1)) +
  scale_x_continuous(breaks = seq(-3, 3, by = 1)) +
theme(
  text = element_text(size = 14),                              # Change the base font size
  axis.title = element_text(size = 16),                        # Change the axis title font size
  axis.text = element_text(size = 14),                         # Change the axis text font size
  legend.text = element_text(size = 14),                       # Change the legend text font size
  legend.title = element_text(size = 14),                     # Change the legend title font size
  plot.title = element_text(size = 18, face = "bold")          # Change the plot title font size and make it bold
)
dev.off()

agg_record_1148129182
                    2

## MFC-DLPFC ICPS

In [3]:
label <- "ICPS_DLPFC"
model <- lmer(ICPS_early_DLPFC_collapsed ~ acc * age_m * soc + sex + dp_inperson + (1 | sub),
              data = tf_data)
summary(model)
# lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: ICPS_early_DLPFC_collapsed ~ acc * age_m * soc + sex + dp_inperson +
    (1 | sub)
   Data: tf_data

REML criterion at convergence: 2146.3

Scaled residuals:
    Min      1Q  Median      3Q     Max
-3.0190 -0.5262 -0.0515  0.4321  4.0769

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.1712   0.4138
 Residual             0.5821   0.7629
Number of obs: 844, groups:  sub, 233

Fixed effects:
                  Estimate Std. Error         df t value Pr(>|t|)
(Intercept)      -0.020438   0.055518 227.364591  -0.368 0.713121
acc1             -0.455084   0.026339 614.763581 -17.278  < 2e-16 ***
age_m             0.204191   0.038211 226.439138   5.344 2.22e-07 ***
soc1             -0.016680   0.026662 650.943589  -0.626 0.531799
sex1              0.023088   0.038110 222.411495   0.606 0.545254
dp_inperson1      0.034419   0.055547 226.426991   0.620 0.536120
acc1:age_m       -0.094600   0.026479 614.884420  -3.573 0.000381 ***
acc1:soc1         0.033431   0.026339 614.974757   1.269 0.204840
age_m:soc1       -0.013400   0.026863 658.313637  -0.499 0.618078
acc1:age_m:soc1   0.006734   0.026504 617.893237   0.254 0.799537
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
            (Intr) acc1   age_m  soc1   sex1   dp_np1 acc1:_ acc1:1 ag_m:1
acc1        -0.013
age_m        0.054 -0.008
soc1        -0.020  0.005  0.025
sex1        -0.019 -0.003  0.015  0.003
dp_inpersn1 -0.727  0.007 -0.068  0.019 -0.025
acc1:age_m  -0.011  0.013 -0.009 -0.005  0.009  0.007
acc1:soc1    0.005 -0.012 -0.004 -0.013  0.001 -0.004  0.025
age_m:soc1   0.027 -0.005  0.002  0.009  0.006 -0.013  0.003 -0.011
acc1:g_m:s1  0.000  0.025  0.002 -0.011  0.009 -0.004  0.000  0.014 -0.008

In [8]:
# test(emtrends(model, pairwise ~ acc | age_m, var="age_m"), adjust="fdr")
# confint(emtrends(model, pairwise ~ acc | age_m, var="age_m"), adjust="fdr")

simple_slopes <- emtrends(model, ~ acc, var = "age_m")

# View the slopes and significance tests (slope != 0)
summary(simple_slopes, infer = c(TRUE, TRUE),
        adjust='fdr',
       )

Cannot use mode = "kenward-roger" because *pbkrtest* package is not installed

NOTE: Results may be misleading due to involvement in interactions

  acc     age_m.trend SE         df       lower.CL    upper.CL  t.ratio
1 Error   0.2987916   0.04667660 457.4166 0.193824943 0.4037582 6.401313
2 Correct 0.1095913   0.04630009 452.3003 0.005467496 0.2137151 2.366978
  p.value
1 7.644664e-10
2 1.835419e-02

In [12]:
library(broom)
library(knitr)

# tidy() converts the object into a clean tibble
tidy_slopes <- tidy(simple_slopes, conf.int = TRUE)

kable(tidy_slopes, digits = 3, format = "simple")

acc        age_m.trend   std.error        df   conf.low   conf.high   statistic   p.value
--------  ------------  ----------  --------  ---------  ----------  ----------  --------
Error            0.299       0.047   457.417      0.207       0.391       6.401     0.000
Correct          0.110       0.046   452.300      0.019       0.201       2.367     0.018

### Plot

In [50]:
# test(emtrends(model, pairwise ~ acc | age_m, var="age_m"), adjust="fdr")
# confint(emtrends(model, pairwise ~ acc | age_m, var="age_m"), adjust="fdr")

y_label = "Frontolateral ICPS"
x_label = "Age"

png(file=sprintf("%s/%s_stats.png", pic_path, label), width=5, height=4, units="in", res=600)
interact_plot(model,
              pred = "age_m",
              modx = "acc",
              interval = 1,
              y.label = y_label,
              x.label = x_label,
              legend.main = "Accuracy",
              colors = c("red", "blue"),
              plot.points = T) +
theme_minimal() +  scale_y_continuous(breaks = seq(-3, 4, by = 1)) +
  scale_x_continuous(breaks = seq(-3, 3, by = 1)) +
theme(
  text = element_text(size = 14),                              # Change the base font size
  axis.title = element_text(size = 16),                        # Change the axis title font size
  axis.text = element_text(size = 14),                         # Change the axis text font size
  legend.text = element_text(size = 14),                       # Change the legend text font size
  legend.title = element_text(size = 14), 
        legend.position = "none", # Change the legend title font size# Change the legend title font size
  plot.title = element_text(size = 18, face = "bold")          # Change the plot title font size and make it bold
)
dev.off()

agg_record_118580619
                   2

## MFC-MOTOR ICPS

In [13]:
label <- "ICPS_MOTOR"
model <- lmer(ICPS_early_MOTOR_collapsed ~ acc * age_m * soc + sex + dp_inperson + (1 | sub),
              data = tf_data)
summary(model)
# lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: ICPS_early_MOTOR_collapsed ~ acc * age_m * soc + sex + dp_inperson +
    (1 | sub)
   Data: tf_data

REML criterion at convergence: 1987

Scaled residuals:
    Min      1Q  Median      3Q     Max
-3.6635 -0.5330 -0.0267  0.4874  3.7932

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.1558   0.3948
 Residual             0.4687   0.6846
Number of obs: 847, groups:  sub, 232

Fixed effects:
                  Estimate Std. Error         df t value Pr(>|t|)
(Intercept)     -2.305e-02  5.116e-02  2.168e+02  -0.451    0.653
acc1            -5.802e-01  2.360e-02  6.114e+02 -24.588  < 2e-16 ***
age_m            1.814e-01  3.534e-02  2.180e+02   5.133 6.30e-07 ***
soc1             1.306e-02  2.390e-02  6.457e+02   0.547    0.585
sex1            -1.381e-02  3.530e-02  2.159e+02  -0.391    0.696
dp_inperson1     4.824e-02  5.120e-02  2.160e+02   0.942    0.347
acc1:age_m      -1.063e-01  2.364e-02  6.120e+02  -4.496 8.28e-06 ***
acc1:soc1       -1.760e-02  2.358e-02  6.087e+02  -0.747    0.456
age_m:soc1       2.041e-02  2.397e-02  6.500e+02   0.851    0.395
acc1:age_m:soc1 -7.141e-04  2.362e-02  6.089e+02  -0.030    0.976
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
            (Intr) acc1   age_m  soc1   sex1   dp_np1 acc1:_ acc1:1 ag_m:1
acc1        -0.006
age_m        0.048 -0.001
soc1        -0.020  0.004  0.025
sex1        -0.015 -0.002  0.019  0.007
dp_inpersn1 -0.724 -0.001 -0.065  0.013 -0.025
acc1:age_m  -0.003  0.008 -0.007  0.001  0.001  0.004
acc1:soc1    0.004 -0.019  0.002 -0.011 -0.004 -0.001  0.026
age_m:soc1   0.025  0.001 -0.015  0.002  0.003 -0.010  0.003  0.000
acc1:g_m:s1  0.004  0.026  0.003  0.000  0.004 -0.003 -0.021  0.006 -0.009

In [15]:
# test(emtrends(model, pairwise ~ acc | age_m, var="age_m"), adjust="fdr")
# confint(emtrends(model, pairwise ~ acc | age_m, var="age_m"), adjust="fdr")

simple_slopes <- emtrends(model, ~ acc, var = "age_m")

# View the slopes and significance tests (slope != 0)
summary(simple_slopes, infer = c(TRUE, TRUE),
        adjust='fdr',
       )

library(broom)
library(knitr)

# tidy() converts the object into a clean tibble
tidy_slopes <- tidy(simple_slopes, conf.int = TRUE)

kable(tidy_slopes, digits = 3, format = "simple")

Cannot use mode = "kenward-roger" because *pbkrtest* package is not installed

NOTE: Results may be misleading due to involvement in interactions

  acc     age_m.trend SE         df       lower.CL    upper.CL  t.ratio
1 Error   0.28769250  0.04265601 431.2919  0.19174823 0.3836368 6.744477
2 Correct 0.07508435  0.04237804 425.7763 -0.02023902 0.1704077 1.771775
  p.value
1 9.905076e-11
2 7.714709e-02

acc        age_m.trend   std.error        df   conf.low   conf.high   statistic   p.value
--------  ------------  ----------  --------  ---------  ----------  ----------  --------
Error            0.288       0.043   431.292      0.204       0.372       6.744     0.000
Correct          0.075       0.042   425.776     -0.008       0.158       1.772     0.077

### Plot

In [48]:
# test(emtrends(model, pairwise ~ acc | age_m, var="age_m"), adjust="fdr")
# confint(emtrends(model, pairwise ~ acc | age_m, var="age_m"), adjust="fdr")

y_label = "Midlateral ICPS"
x_label = "Age"

png(file=sprintf("%s/%s_stats.png", pic_path, label), width=5, height=4, units="in", res=600)
interact_plot(model,
              pred = "age_m",
              modx = "acc",
              interval = 1,
              y.label = y_label,
              x.label = x_label,
              legend.main = "Accuracy",
              colors = c("red", "blue"),
              plot.points = T) +
theme_minimal() +  scale_y_continuous(breaks = seq(-3, 4, by = 1)) +
  scale_x_continuous(breaks = seq(-3, 3, by = 1)) +
theme(
  text = element_text(size = 14),                              # Change the base font size
  axis.title = element_text(size = 16),                        # Change the axis title font size
  axis.text = element_text(size = 14),                         # Change the axis text font size
  legend.text = element_text(size = 14),                       # Change the legend text font size
  legend.title = element_text(size = 14),
    legend.position = "none", # Change the legend title font size
  plot.title = element_text(size = 18, face = "bold")          # Change the plot title font size and make it bold
)
dev.off()

agg_record_909403265
                   2

## MFC-OCC ICPS

In [54]:
label <- "ICPS_OCC"
model <- lmer(ICPS_early_OCC_collapsed ~ acc * age_m * soc + sex + dp_inperson + (1 | sub),
              data = tf_data)
summary(model)
lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: ICPS_early_OCC_collapsed ~ acc * age_m * soc + sex + dp_inperson +
    (1 | sub)
   Data: tf_data

REML criterion at convergence: 2210.6

Scaled residuals:
    Min      1Q  Median      3Q     Max
-2.7694 -0.5643  0.0088  0.5157  4.0000

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.2195   0.4685
 Residual             0.6217   0.7885
Number of obs: 839, groups:  sub, 233

Fixed effects:
                  Estimate Std. Error         df t value Pr(>|t|)
(Intercept)       0.018767   0.059943 218.351210   0.313   0.7545
acc1             -0.398289   0.027345 609.370861 -14.565   <2e-16 ***
age_m             0.059511   0.041542 222.836668   1.433   0.1534
soc1              0.004286   0.027692 641.611122   0.155   0.8770
sex1             -0.068712   0.041450 219.287998  -1.658   0.0988 .
dp_inperson1     -0.011619   0.059974 217.475762  -0.194   0.8466
acc1:age_m        0.006544   0.027473 608.506931   0.238   0.8118
acc1:soc1         0.003570   0.027306 605.667511   0.131   0.8960
age_m:soc1       -0.050063   0.027917 650.173003  -1.793   0.0734 .
acc1:age_m:soc1   0.062805   0.027460 607.261384   2.287   0.0225 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
            (Intr) acc1   age_m  soc1   sex1   dp_np1 acc1:_ acc1:1 ag_m:1
acc1        -0.007
age_m        0.050  0.002
soc1        -0.019  0.006  0.027
sex1        -0.015  0.001  0.017  0.010
dp_inpersn1 -0.722 -0.003 -0.063  0.014 -0.026
acc1:age_m  -0.002  0.011 -0.015  0.002  0.004  0.004
acc1:soc1    0.005 -0.016  0.003 -0.017  0.001  0.000  0.031
age_m:soc1   0.026  0.002 -0.014  0.007  0.006 -0.010  0.012  0.001
acc1:g_m:s1  0.004  0.031  0.012  0.001  0.006 -0.002 -0.021  0.009 -0.021

Computing profile confidence intervals ...

In [62]:
# test(emtrends(model, pairwise ~ acc | age_m, var="age_m"), adjust="fdr")
# confint(emtrends(model, pairwise ~ acc | age_m, var="age_m"), adjust="fdr")

simple_slopes <- emtrends(model, ~ acc | soc, var = "age_m")

# View the slopes and significance tests (slope != 0)
summary(simple_slopes, infer = c(TRUE, TRUE),
        adjust='fdr'
       )

diff_slopes <- contrast(simple_slopes, method = "revpairwise", by = "soc")

# View differences and significance tests
summary(diff_slopes, infer = c(TRUE, TRUE),
        adjust='fdr'
       )

diff_slopes <- contrast(simple_slopes, method = "revpairwise", by = "acc")

# View differences and significance tests
summary(diff_slopes, infer = c(TRUE, TRUE),
        adjust='fdr'
       )

Cannot use mode = "kenward-roger" because *pbkrtest* package is not installed

  acc     soc age_m.trend SE         df       lower.CL    upper.CL   t.ratio
1 Error   NS   0.16583484 0.06474164 737.2565  0.02042576 0.31124393  2.5614867
2 Correct NS   0.05331330 0.06297372 720.7926 -0.08813167 0.19475826  0.8465960
3 Error   S   -0.05990113 0.06300423 720.7878 -0.20141462 0.08161236 -0.9507479
4 Correct S    0.07879570 0.06268348 716.4674 -0.06199913 0.21959054  1.2570410
  p.value
1 0.02124066
2 0.39750133
3 0.34205107
4 0.34205107

  contrast        soc estimate   SE         df       lower.CL   upper.CL
1 Correct - Error NS  -0.1125215 0.07850276 610.3177 -0.2666899 0.04164678
2 Correct - Error S    0.1386968 0.07686341 605.3476 -0.0122545 0.28964817
  t.ratio   p.value
1 -1.433345 0.15227133
2  1.804458 0.07165635

  contrast acc     estimate    SE         df       lower.CL   upper.CL
1 S - NS   Error   -0.22573597 0.07915113 631.9718 -0.3811670 -0.07030494
2 S - NS   Correct  0.02548241 0.07747581 626.0983 -0.1266615  0.17762632
  t.ratio    p.value
1 -2.8519615 0.004487013
2  0.3289079 0.742335310

### Plot

In [67]:
# test(emtrends(model, pairwise ~ acc | age_m, var="age_m"), adjust="fdr")
# confint(emtrends(model, pairwise ~ acc | age_m, var="age_m"), adjust="fdr")

y_label = "Posterolateral ICPS"
x_label = "Age"
cond_labels = c("Non-social", "Social")

png(file=sprintf("%s/%s_stats.png", pic_path, label), width=8, height=5, units="in", res=600)
interact_plot(model,
              pred = "age_m",
              modx = "acc",
              mod2="soc",
              interval = 1,
              y.label = y_label,
              x.label = x_label,
              colors = c("red", "blue"),
              legend.main = "Accuracy",
              mod2.labels = cond_labels,
              plot.points = T) +
  theme_minimal() +
  theme(
    text = element_text(size = 20),                              # Change the base font size
    axis.title = element_text(size = 16),                        # Change the axis title font size
    axis.text = element_text(size = 14),                         # Change the axis text font size
    legend.text = element_text(size = 14),                       # Change the legend text font size
    legend.title = element_text(size = 14),                     # Change the legend title font size
    plot.title = element_text(size = 20, face = "bold")          # Change the plot title font size and make it bold
  ) +
  scale_y_continuous(breaks = seq(-3, 3, by = 1)) +
  scale_x_continuous(breaks = seq(-1, 1, by = 1))
  # scale_linetype_manual(values = c("solid", "solid"))
dev.off()

agg_record_1006651352
                    2

# DDM measures predicted by ICPS

## Load data

In [5]:
rm(list = ls())
session = "s1_r1"
analysis_path = "/home/data/NDClab/analyses/thrive-theta-ddm/"
source(sprintf("%s/code/statistics/lmer_export_apa.R", analysis_path))
source(sprintf("%s/code/statistics/find_newest_file.R", analysis_path))
pic_path <- (sprintf("%s/derivatives/figs/%s", analysis_path, session))
# tf_data <- read.csv("/Users/fzaki001/IDENTIFIABLE/tf_data_collapsed_merged.csv")
tf_data <- read.csv(find_newest_file(sprintf("%s/derivatives/csv/%s/thrive*long*.csv", analysis_path, session)))
table_output_path = sprintf("%s/derivatives/statistics/full_sample/", analysis_path)

# it doesnt matter 0 or 1 because the models below use difference scores; because of that we need to get rid of duplicates (diff scores are the same for acc=0 and acc=1)
id_cols <- c('sub', 'age_m', 'sex', 'acc', 'soc', 'dp_inperson', 'first_soc')
data_cols <- c(
    'reversed_ratio_diff',
    'a_diff',
    'p_diff',
    'ter_diff',
    'ICPS_early_DLPFC_diff_collapsed',
    'ICPS_early_MOTOR_diff_collapsed',
    'ICPS_early_OCC_diff_collapsed'
)
tf_data <- tf_data[, c(id_cols, data_cols)]
tf_data <- tf_data %>%
  filter(!if_all(c(data_cols), is.na))
tf_data <- subset(tf_data, tf_data$acc == 1)

tf_data$sub <- as.factor(tf_data$sub)
tf_data$soc <- as.factor(tf_data$soc)
tf_data$sex <- as.factor(tf_data$sex)
tf_data$acc <- as.factor(tf_data$acc)
tf_data$first_soc <- as.factor(tf_data$first_soc)
# tf_data$task_num <- as.factor(tf_data$task_num)
tf_data$dp_inperson <- as.factor(tf_data$dp_inperson)

tf_data[c("age_m", data_cols)] <- as.data.frame(scale(tf_data[c("age_m", data_cols)]))

tf_data$soc <- revalue(tf_data$soc, c("0" = "NS", "1" = "S"))
tf_data$sex <- revalue(tf_data$sex, c("1" = "M", "2" = "F"))

# contrasts(tf_data$acc) <- rev(contr.sum(2))
contrasts(tf_data$sex) <- rev(contr.sum(2))
contrasts(tf_data$soc) <- rev(contr.sum(2))
contrasts(tf_data$first_soc) <- rev(contr.sum(2))
# contrasts(tf_data$task_num) <- rev(contr.sum(2))
contrasts(tf_data$dp_inperson) <- rev(contr.sum(2))

[1] "The newest file is: /home/data/NDClab/analyses/thrive-theta-ddm//derivatives/csv/s1_r1/thrive_long_s1_r1_22_02_2026_23_31_39.csv"

## sda/rd (attentional ratio)

In [22]:
label <- "ratio_reversed"
plot_label <- bquote(atop("Attentional Control", sd[a] / r[d] ~ "(Post-error - Post-correct)"))
model <- lmer(reversed_ratio_diff ~ ICPS_early_OCC_diff_collapsed * age_m  * soc + ICPS_early_DLPFC_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub),
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Correlation matrix not shown by default, as p = 14 > 12.
Use print(obj, correlation=TRUE)  or
    vcov(obj)        if you need it

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: reversed_ratio_diff ~ ICPS_early_OCC_diff_collapsed * age_m *
    soc + ICPS_early_DLPFC_diff_collapsed * age_m * soc + sex +
    dp_inperson + (1 | sub)
   Data: tf_data

REML criterion at convergence: 1034

Scaled residuals:
     Min       1Q   Median       3Q      Max
-2.38629 -0.63160  0.05079  0.58236  2.54333

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.1343   0.3665
 Residual             0.8772   0.9366
Number of obs: 350, groups:  sub, 209

Fixed effects:
                                             Estimate Std. Error         df
(Intercept)                                 -0.036284   0.082481 197.208176
ICPS_early_OCC_diff_collapsed                0.156533   0.059939 317.098200
age_m                                        0.008302   0.058737 181.065772
soc1                                        -0.051132   0.051693 172.715766
ICPS_early_DLPFC_diff_collapsed             -0.004581   0.061913 334.686257
sex1                                        -0.027811   0.056933 175.963695
dp_inperson1                                 0.058550   0.082139 196.255667
ICPS_early_OCC_diff_collapsed:age_m          0.019744   0.062011 327.516947
ICPS_early_OCC_diff_collapsed:soc1           0.063132   0.057548 280.834162
age_m:soc1                                   0.020168   0.052762 173.286038
age_m:ICPS_early_DLPFC_diff_collapsed        0.024056   0.065576 335.481484
soc1:ICPS_early_DLPFC_diff_collapsed        -0.020398   0.060792 313.904115
ICPS_early_OCC_diff_collapsed:age_m:soc1    -0.012800   0.060207 292.587795
age_m:soc1:ICPS_early_DLPFC_diff_collapsed   0.003593   0.064650 315.376956
                                           t value Pr(>|t|)
(Intercept)                                 -0.440  0.66048
ICPS_early_OCC_diff_collapsed                2.612  0.00944 **
age_m                                        0.141  0.88776
soc1                                        -0.989  0.32397
ICPS_early_DLPFC_diff_collapsed             -0.074  0.94106
sex1                                        -0.488  0.62582
dp_inperson1                                 0.713  0.47681
ICPS_early_OCC_diff_collapsed:age_m          0.318  0.75040
ICPS_early_OCC_diff_collapsed:soc1           1.097  0.27357
age_m:soc1                                   0.382  0.70275
age_m:ICPS_early_DLPFC_diff_collapsed        0.367  0.71396
soc1:ICPS_early_DLPFC_diff_collapsed        -0.336  0.73745
ICPS_early_OCC_diff_collapsed:age_m:soc1    -0.213  0.83179
age_m:soc1:ICPS_early_DLPFC_diff_collapsed   0.056  0.95571
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Computing profile confidence intervals ...

### Plot

In [23]:
png(file=sprintf("%s/%s_stats.png", pic_path, label), width=9, height=5, units="in", res=600)
g <- ggplot(data = tf_data, aes(x = ICPS_early_OCC_diff_collapsed, y = reversed_ratio_diff))
g + geom_smooth(method = "lm") + geom_point() + labs(y=plot_label, x="Midfrontal-Posterolateral ICPS (Error - Correct)") +
  theme_minimal() +
  theme(
    text = element_text(size = 14),                              # Change the base font size
    axis.title = element_text(size = 16),                        # Change the axis title font size
    axis.text = element_text(size = 14),                         # Change the axis text font size
    plot.title = element_text(size = 18, face = "bold")          # Change the plot title font size and make it bold
  ) +
  scale_y_continuous(breaks = seq(-1, 1, by = 1)) +
  scale_x_continuous(breaks = seq(-3, 3, by = 1))
dev.off()

`geom_smooth()` using formula = 'y ~ x'
Warning message:
"Removed 77 rows containing non-finite outside the scale range
(`stat_smooth()`)."
Warning message:
"Removed 77 rows containing missing values or values outside the scale range
(`geom_point()`)."

agg_record_140738080
                   2

In [30]:
label <- "ratio_reversed_motor"
plot_label <- bquote(paste('Attentional Control', 'sd'['a'], '/r'['d'], '(Post-error - Post-correct)'))
model <- lmer(reversed_ratio_diff ~ ICPS_early_MOTOR_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub),
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: reversed_ratio_diff ~ ICPS_early_MOTOR_diff_collapsed * age_m *
    soc + sex + dp_inperson + (1 | sub)
   Data: tf_data

REML criterion at convergence: 1070.9

Scaled residuals:
     Min       1Q   Median       3Q      Max
-2.43515 -0.60592  0.02835  0.57791  2.56940

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.1570   0.3962
 Residual             0.8622   0.9286
Number of obs: 366, groups:  sub, 214

Fixed effects:
                                             Estimate Std. Error         df
(Intercept)                                -5.879e-02  8.170e-02  2.085e+02
ICPS_early_MOTOR_diff_collapsed             4.220e-02  5.880e-02  3.179e+02
age_m                                      -2.669e-02  5.811e-02  1.983e+02
soc1                                       -5.748e-02  5.008e-02  1.860e+02
sex1                                       -3.194e-02  5.626e-02  1.933e+02
dp_inperson1                                5.571e-02  8.085e-02  2.057e+02
ICPS_early_MOTOR_diff_collapsed:age_m       8.359e-02  5.931e-02  3.317e+02
ICPS_early_MOTOR_diff_collapsed:soc1        5.351e-02  5.494e-02  2.649e+02
age_m:soc1                                 -1.072e-03  5.124e-02  1.902e+02
ICPS_early_MOTOR_diff_collapsed:age_m:soc1 -8.175e-04  5.586e-02  2.892e+02
                                           t value Pr(>|t|)
(Intercept)                                 -0.720    0.473
ICPS_early_MOTOR_diff_collapsed              0.718    0.474
age_m                                       -0.459    0.647
soc1                                        -1.148    0.253
sex1                                        -0.568    0.571
dp_inperson1                                 0.689    0.492
ICPS_early_MOTOR_diff_collapsed:age_m        1.409    0.160
ICPS_early_MOTOR_diff_collapsed:soc1         0.974    0.331
age_m:soc1                                  -0.021    0.983
ICPS_early_MOTOR_diff_collapsed:age_m:soc1  -0.015    0.988

Correlation of Fixed Effects:
                 (Intr) ICPS_r_MOTOR__ age_m  soc1   sex1   dp_np1
ICPS_r_MOTOR__    0.071
age_m             0.052 -0.152
soc1             -0.057 -0.066          0.027
sex1             -0.002  0.069         -0.011  0.004
dp_inpersn1      -0.718 -0.084         -0.052  0.036 -0.011
ICPS_r_MOTOR__:_ -0.194 -0.179         -0.041  0.011 -0.043  0.115
ICPS__MOTOR__:1  -0.005 -0.084          0.025  0.017  0.057 -0.043
age_m:soc1        0.012  0.023         -0.017  0.029 -0.017  0.012
ICPS__MOTOR__:_:  0.013  0.029         -0.035 -0.168  0.010 -0.012
                 ICPS_r_MOTOR__:_ ICPS__MOTOR__:1 ag_m:1
ICPS_r_MOTOR__
age_m
soc1
sex1
dp_inpersn1
ICPS_r_MOTOR__:_
ICPS__MOTOR__:1   0.022
age_m:soc1       -0.048           -0.162
ICPS__MOTOR__:_:  0.062           -0.158          -0.035

Computing profile confidence intervals ...

## a (boundary separation)

In [22]:
label <- "boundary_separation"
# plot_label <- bquote(atop("Boundary Separation", italic(ɑ) ~ "(Post-error - Post-correct)"))
model <- lmer(a_diff ~ ICPS_early_OCC_diff_collapsed * age_m  * soc + ICPS_early_DLPFC_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub), 
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Correlation matrix not shown by default, as p = 14 > 12.
Use print(obj, correlation=TRUE)  or
    vcov(obj)        if you need it

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula:
a_diff ~ ICPS_early_OCC_diff_collapsed * age_m * soc + ICPS_early_DLPFC_diff_collapsed *
    age_m * soc + sex + dp_inperson + (1 | sub)
   Data: tf_data

REML criterion at convergence: 1005.7

Scaled residuals:
     Min       1Q   Median       3Q      Max
-2.74115 -0.66669 -0.04045  0.69570  2.56846

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.02404  0.1551
 Residual             0.93066  0.9647
Number of obs: 346, groups:  sub, 207

Fixed effects:
                                             Estimate Std. Error         df
(Intercept)                                  0.005964   0.078756 195.409592
ICPS_early_OCC_diff_collapsed                0.099667   0.057952 303.586318
age_m                                        0.105262   0.055069 175.075522
soc1                                         0.011053   0.052901 175.736139
ICPS_early_DLPFC_diff_collapsed              0.015738   0.060738 326.199598
sex1                                         0.136107   0.053418 171.722106
dp_inperson1                                 0.029459   0.078520 196.082377
ICPS_early_OCC_diff_collapsed:age_m          0.081737   0.060058 311.983466
ICPS_early_OCC_diff_collapsed:soc1           0.004955   0.057441 297.725617
age_m:soc1                                   0.054138   0.053787 174.211287
age_m:ICPS_early_DLPFC_diff_collapsed       -0.185874   0.064260 327.145234
soc1:ICPS_early_DLPFC_diff_collapsed         0.021555   0.060560 323.895536
ICPS_early_OCC_diff_collapsed:age_m:soc1    -0.010087   0.059717 307.176541
age_m:soc1:ICPS_early_DLPFC_diff_collapsed  -0.054412   0.064214 323.572864
                                           t value Pr(>|t|)
(Intercept)                                  0.076  0.93971
ICPS_early_OCC_diff_collapsed                1.720  0.08648 .
age_m                                        1.911  0.05758 .
soc1                                         0.209  0.83473
ICPS_early_DLPFC_diff_collapsed              0.259  0.79571
sex1                                         2.548  0.01171 *
dp_inperson1                                 0.375  0.70793
ICPS_early_OCC_diff_collapsed:age_m          1.361  0.17450
ICPS_early_OCC_diff_collapsed:soc1           0.086  0.93131
age_m:soc1                                   1.007  0.31556
age_m:ICPS_early_DLPFC_diff_collapsed       -2.893  0.00408 **
soc1:ICPS_early_DLPFC_diff_collapsed         0.356  0.72213
ICPS_early_OCC_diff_collapsed:age_m:soc1    -0.169  0.86597
age_m:soc1:ICPS_early_DLPFC_diff_collapsed  -0.847  0.39742
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Computing profile confidence intervals ...

### Plot

In [40]:
png(file=sprintf("%s/%s_stats.png", pic_path, label), width=9, height=5, units="in", res=600)
interact_plot(model, pred = "ICPS_early_DLPFC_diff_collapsed", modx = "age_m", interval = 1, dodge.width = 0.2,
              y.label = plot_label,
              x.label = "Midfrontal-Frontolateral ICPS (Error - Correct)",
              legend.main = "Age",
              plot.points = T) + 
  theme_minimal() +
  theme(
    text = element_text(size = 14), # Change the base font size
    axis.title = element_text(size = 16),                        # Change the axis title font size
    axis.text = element_text(size = 14),                         # Change the axis text font size
    # legend.text = element_text(size = 14),                       # Change the legend text font size
    # legend.title = element_text(size = 14),                     # Change the legend title font size
    plot.title = element_text(size = 18, face = "bold")         # Change the plot title font size and make it bold
  ) + theme(legend.position = "none") +
  scale_y_continuous(breaks = seq(-3, 3, by = 1)) +
  scale_x_continuous(breaks = seq(-3, 3, by = 1)) + theme(legend.position = "bottom")
dev.off()

agg_record_481391806
                   2

In [32]:
label <- "boundary separation_motor"
model <- lmer(a_diff ~ ICPS_early_MOTOR_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub),
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: a_diff ~ ICPS_early_MOTOR_diff_collapsed * age_m * soc + sex +
    dp_inperson + (1 | sub)
   Data: tf_data

REML criterion at convergence: 1056.4

Scaled residuals:
     Min       1Q   Median       3Q      Max
-2.74175 -0.64152 -0.01014  0.64604  2.64944

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.04712  0.2171
 Residual             0.95413  0.9768
Number of obs: 362, groups:  sub, 212

Fixed effects:
                                            Estimate Std. Error        df
(Intercept)                                 -0.01668    0.07946 203.51163
ICPS_early_MOTOR_diff_collapsed              0.02076    0.05770 295.71571
age_m                                        0.10671    0.05567 189.96732
soc1                                        -0.03466    0.05249 186.74996
sex1                                         0.12530    0.05393 187.23521
dp_inperson1                                 0.04523    0.07856 201.13395
ICPS_early_MOTOR_diff_collapsed:age_m       -0.10221    0.05824 313.24882
ICPS_early_MOTOR_diff_collapsed:soc1        -0.04857    0.05636 278.74869
age_m:soc1                                   0.03524    0.05352 188.84173
ICPS_early_MOTOR_diff_collapsed:age_m:soc1   0.05141    0.05683 299.29089
                                           t value Pr(>|t|)
(Intercept)                                 -0.210   0.8340
ICPS_early_MOTOR_diff_collapsed              0.360   0.7193
age_m                                        1.917   0.0568 .
soc1                                        -0.660   0.5098
sex1                                         2.323   0.0212 *
dp_inperson1                                 0.576   0.5654
ICPS_early_MOTOR_diff_collapsed:age_m       -1.755   0.0802 .
ICPS_early_MOTOR_diff_collapsed:soc1        -0.862   0.3896
age_m:soc1                                   0.658   0.5110
ICPS_early_MOTOR_diff_collapsed:age_m:soc1   0.905   0.3664
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
                 (Intr) ICPS_r_MOTOR__ age_m  soc1   sex1   dp_np1
ICPS_r_MOTOR__    0.066
age_m             0.051 -0.157
soc1             -0.046 -0.068          0.040
sex1             -0.003  0.084         -0.016 -0.007
dp_inpersn1      -0.727 -0.074         -0.057  0.021  0.000
ICPS_r_MOTOR__:_ -0.203 -0.177         -0.040  0.011 -0.039  0.123
ICPS__MOTOR__:1  -0.016 -0.083          0.028  0.018  0.056 -0.038
age_m:soc1        0.016  0.024         -0.024  0.016 -0.015  0.017
ICPS__MOTOR__:_:  0.014  0.031         -0.040 -0.169  0.006 -0.011
                 ICPS_r_MOTOR__:_ ICPS__MOTOR__:1 ag_m:1
ICPS_r_MOTOR__
age_m
soc1
sex1
dp_inpersn1
ICPS_r_MOTOR__:_
ICPS__MOTOR__:1   0.024
age_m:soc1       -0.042           -0.164
ICPS__MOTOR__:_:  0.062           -0.163          -0.035

Computing profile confidence intervals ...

# Behavioral post-error adjustments measures predicted by ICPS

## Load data

In [33]:
rm(list = ls())
session = "s1_r1"
analysis_path = "/home/data/NDClab/analyses/thrive-theta-ddm/"
source(sprintf("%s/code/statistics/lmer_export_apa.R", analysis_path))
source(sprintf("%s/code/statistics/find_newest_file.R", analysis_path))
pic_path <- (sprintf("%s/derivatives/figs/%s", analysis_path, session))
# tf_data <- read.csv("/Users/fzaki001/IDENTIFIABLE/tf_data_collapsed_merged.csv")
tf_data <- read.csv(find_newest_file(sprintf("%s/derivatives/csv/%s/thrive*long*.csv", analysis_path, session)))
table_output_path = sprintf("%s/derivatives/statistics/full_sample/", analysis_path)

# it doesnt matter 0 or 1 because the models below use difference scores; because of that we need to get rid of duplicates (diff scores are the same for acc=0 and acc=1)
id_cols <- c('sub', 'age_m', 'sex', 'acc', 'soc', 'dp_inperson', 'first_soc')
data_cols <- c(
    'pea',
    'peri_rt',
    'pes',
    'ICPS_early_DLPFC_diff_collapsed',
    'ICPS_early_MOTOR_diff_collapsed',
    'ICPS_early_OCC_diff_collapsed'
)
tf_data <- tf_data[, c(id_cols, data_cols)]
tf_data <- tf_data %>%
  filter(!if_all(c(data_cols), is.na))
tf_data <- subset(tf_data, tf_data$acc == 1)

tf_data$sub <- as.factor(tf_data$sub)
tf_data$soc <- as.factor(tf_data$soc)
tf_data$sex <- as.factor(tf_data$sex)
tf_data$acc <- as.factor(tf_data$acc)
tf_data$first_soc <- as.factor(tf_data$first_soc)
# tf_data$task_num <- as.factor(tf_data$task_num)
tf_data$dp_inperson <- as.factor(tf_data$dp_inperson)

tf_data[c("age_m", data_cols)] <- as.data.frame(scale(tf_data[c("age_m", data_cols)]))

tf_data$soc <- revalue(tf_data$soc, c("0" = "NS", "1" = "S"))
tf_data$sex <- revalue(tf_data$sex, c("1" = "M", "2" = "F"))
# tf_data$acc <- revalue(tf_data$acc, c("0" = "Error", "1" = "Correct"))

# contrasts(tf_data$acc) <- rev(contr.sum(2))
contrasts(tf_data$sex) <- rev(contr.sum(2))
contrasts(tf_data$soc) <- rev(contr.sum(2))
contrasts(tf_data$first_soc) <- rev(contr.sum(2))
# contrasts(tf_data$task_num) <- rev(contr.sum(2))
contrasts(tf_data$dp_inperson) <- rev(contr.sum(2))

[1] "The newest file is: /home/data/NDClab/analyses/thrive-theta-ddm//derivatives/csv/s1_r1/thrive_long_s1_r1_17_01_2026_19_46_00.csv"

## PEA

In [34]:
label <- "PEA"
model <- lmer(pea ~ ICPS_early_OCC_diff_collapsed * age_m  * soc + ICPS_early_DLPFC_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub), 
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Correlation matrix not shown by default, as p = 14 > 12.
Use print(obj, correlation=TRUE)  or
    vcov(obj)        if you need it

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula:
pea ~ ICPS_early_OCC_diff_collapsed * age_m * soc + ICPS_early_DLPFC_diff_collapsed *
    age_m * soc + sex + dp_inperson + (1 | sub)
   Data: tf_data

REML criterion at convergence: 1092.8

Scaled residuals:
    Min      1Q  Median      3Q     Max
-3.5121 -0.5077  0.0688  0.6025  2.4833

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.09746  0.3122
 Residual             0.84050  0.9168
Number of obs: 379, groups:  sub, 218

Fixed effects:
                                             Estimate Std. Error         df
(Intercept)                                 -0.078972   0.075825 200.302530
ICPS_early_OCC_diff_collapsed                0.105340   0.051838 348.954162
age_m                                        0.170152   0.053309 197.284888
soc1                                        -0.042320   0.048503 189.223596
ICPS_early_DLPFC_diff_collapsed             -0.002235   0.053180 361.364725
sex1                                         0.058398   0.052145 187.267214
dp_inperson1                                 0.075956   0.075457 199.891524
ICPS_early_OCC_diff_collapsed:age_m          0.081341   0.049324 363.901902
ICPS_early_OCC_diff_collapsed:soc1           0.035890   0.050457 321.430225
age_m:soc1                                   0.054804   0.048862 192.342594
age_m:ICPS_early_DLPFC_diff_collapsed       -0.022738   0.050851 360.612036
soc1:ICPS_early_DLPFC_diff_collapsed         0.057463   0.052368 345.505375
ICPS_early_OCC_diff_collapsed:age_m:soc1    -0.040913   0.048738 351.227328
age_m:soc1:ICPS_early_DLPFC_diff_collapsed  -0.050750   0.050233 350.573038
                                           t value Pr(>|t|)
(Intercept)                                 -1.042  0.29889
ICPS_early_OCC_diff_collapsed                2.032  0.04290 *
age_m                                        3.192  0.00165 **
soc1                                        -0.873  0.38403
ICPS_early_DLPFC_diff_collapsed             -0.042  0.96649
sex1                                         1.120  0.26418
dp_inperson1                                 1.007  0.31533
ICPS_early_OCC_diff_collapsed:age_m          1.649  0.09999 .
ICPS_early_OCC_diff_collapsed:soc1           0.711  0.47741
age_m:soc1                                   1.122  0.26342
age_m:ICPS_early_DLPFC_diff_collapsed       -0.447  0.65504
soc1:ICPS_early_DLPFC_diff_collapsed         1.097  0.27328
ICPS_early_OCC_diff_collapsed:age_m:soc1    -0.839  0.40179
age_m:soc1:ICPS_early_DLPFC_diff_collapsed  -1.010  0.31306
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Computing profile confidence intervals ...

In [35]:
label <- "PEA_motor"
model <- lmer(pea ~ ICPS_early_MOTOR_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub), 
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula:
pea ~ ICPS_early_MOTOR_diff_collapsed * age_m * soc + sex + dp_inperson +
    (1 | sub)
   Data: tf_data

REML criterion at convergence: 1166.2

Scaled residuals:
    Min      1Q  Median      3Q     Max
-3.2075 -0.5255  0.0365  0.6085  2.7822

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.1598   0.3998
 Residual             0.8044   0.8969
Number of obs: 407, groups:  sub, 225

Fixed effects:
                                             Estimate Std. Error         df
(Intercept)                                 -0.055345   0.075926 214.446803
ICPS_early_MOTOR_diff_collapsed              0.071772   0.051367 369.617960
age_m                                        0.162430   0.053000 218.871281
soc1                                        -0.035989   0.045719 208.137355
sex1                                         0.048018   0.052437 210.777741
dp_inperson1                                 0.069584   0.075135 210.544342
ICPS_early_MOTOR_diff_collapsed:age_m       -0.028416   0.049957 390.813943
ICPS_early_MOTOR_diff_collapsed:soc1         0.049719   0.048246 311.163513
age_m:soc1                                   0.004395   0.045891 213.011290
ICPS_early_MOTOR_diff_collapsed:age_m:soc1  -0.019612   0.047777 351.293392
                                           t value Pr(>|t|)
(Intercept)                                 -0.729  0.46684
ICPS_early_MOTOR_diff_collapsed              1.397  0.16318
age_m                                        3.065  0.00245 **
soc1                                        -0.787  0.43208
sex1                                         0.916  0.36086
dp_inperson1                                 0.926  0.35544
ICPS_early_MOTOR_diff_collapsed:age_m       -0.569  0.56981
ICPS_early_MOTOR_diff_collapsed:soc1         1.031  0.30357
age_m:soc1                                   0.096  0.92380
ICPS_early_MOTOR_diff_collapsed:age_m:soc1  -0.411  0.68169
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
                 (Intr) ICPS_r_MOTOR__ age_m  soc1   sex1   dp_np1
ICPS_r_MOTOR__    0.053
age_m             0.039 -0.165
soc1             -0.034 -0.045          0.038
sex1             -0.001  0.060          0.018  0.000
dp_inpersn1      -0.717 -0.048         -0.054  0.021 -0.017
ICPS_r_MOTOR__:_ -0.179 -0.184          0.005  0.019 -0.064  0.089
ICPS__MOTOR__:1   0.014 -0.038          0.036  0.027  0.056 -0.053
age_m:soc1        0.032  0.038         -0.026  0.000 -0.018 -0.005
ICPS__MOTOR__:_:  0.012 -0.006         -0.061 -0.184  0.024 -0.002
                 ICPS_r_MOTOR__:_ ICPS__MOTOR__:1 ag_m:1
ICPS_r_MOTOR__
age_m
soc1
sex1
dp_inpersn1
ICPS_r_MOTOR__:_
ICPS__MOTOR__:1  -0.012
age_m:soc1       -0.077           -0.185
ICPS__MOTOR__:_:  0.035           -0.145           0.016

Computing profile confidence intervals ...

## PERI

In [36]:
label <- "PERI"
model <- lmer(peri_rt ~ ICPS_early_OCC_diff_collapsed * age_m  * soc + ICPS_early_DLPFC_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub), 
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Correlation matrix not shown by default, as p = 14 > 12.
Use print(obj, correlation=TRUE)  or
    vcov(obj)        if you need it

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula:
peri_rt ~ ICPS_early_OCC_diff_collapsed * age_m * soc + ICPS_early_DLPFC_diff_collapsed *
    age_m * soc + sex + dp_inperson + (1 | sub)
   Data: tf_data

REML criterion at convergence: 1093.1

Scaled residuals:
    Min      1Q  Median      3Q     Max
-3.3584 -0.5425 -0.0293  0.5801  2.9487

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.08585  0.293
 Residual             0.86682  0.931
Number of obs: 377, groups:  sub, 217

Fixed effects:
                                             Estimate Std. Error         df
(Intercept)                                  0.029741   0.076707 215.526482
ICPS_early_OCC_diff_collapsed               -0.005724   0.052969 347.546032
age_m                                       -0.022499   0.053734 208.883185
soc1                                         0.075249   0.049376 201.550542
ICPS_early_DLPFC_diff_collapsed              0.048772   0.054088 359.385429
sex1                                        -0.023461   0.052401 198.500397
dp_inperson1                                -0.013932   0.076239 214.586392
ICPS_early_OCC_diff_collapsed:age_m          0.007735   0.050388 361.750834
ICPS_early_OCC_diff_collapsed:soc1           0.005594   0.051720 326.343858
age_m:soc1                                   0.045962   0.049853 205.281581
age_m:ICPS_early_DLPFC_diff_collapsed        0.024154   0.052042 358.698292
soc1:ICPS_early_DLPFC_diff_collapsed        -0.019489   0.053412 347.070126
ICPS_early_OCC_diff_collapsed:age_m:soc1     0.039016   0.049830 351.863501
age_m:soc1:ICPS_early_DLPFC_diff_collapsed   0.033524   0.051439 350.589365
                                           t value Pr(>|t|)
(Intercept)                                  0.388    0.699
ICPS_early_OCC_diff_collapsed               -0.108    0.914
age_m                                       -0.419    0.676
soc1                                         1.524    0.129
ICPS_early_DLPFC_diff_collapsed              0.902    0.368
sex1                                        -0.448    0.655
dp_inperson1                                -0.183    0.855
ICPS_early_OCC_diff_collapsed:age_m          0.153    0.878
ICPS_early_OCC_diff_collapsed:soc1           0.108    0.914
age_m:soc1                                   0.922    0.358
age_m:ICPS_early_DLPFC_diff_collapsed        0.464    0.643
soc1:ICPS_early_DLPFC_diff_collapsed        -0.365    0.715
ICPS_early_OCC_diff_collapsed:age_m:soc1     0.783    0.434
age_m:soc1:ICPS_early_DLPFC_diff_collapsed   0.652    0.515

Computing profile confidence intervals ...

In [37]:
label <- "PERI_motor"
model <- lmer(peri_rt ~ ICPS_early_MOTOR_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub), 
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: peri_rt ~ ICPS_early_MOTOR_diff_collapsed * age_m * soc + sex +
    dp_inperson + (1 | sub)
   Data: tf_data

REML criterion at convergence: 1181.3

Scaled residuals:
    Min      1Q  Median      3Q     Max
-3.4106 -0.5572 -0.0146  0.5841  2.9674

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.05914  0.2432
 Residual             0.93866  0.9688
Number of obs: 406, groups:  sub, 227

Fixed effects:
                                             Estimate Std. Error         df
(Intercept)                                  0.013553   0.074477 210.107070
ICPS_early_MOTOR_diff_collapsed             -0.044827   0.052063 347.766792
age_m                                       -0.013115   0.052148 215.715116
soc1                                         0.113377   0.049047 207.537956
sex1                                         0.001365   0.051171 206.090270
dp_inperson1                                -0.012686   0.073768 207.618487
ICPS_early_MOTOR_diff_collapsed:age_m        0.016799   0.051647 380.223766
ICPS_early_MOTOR_diff_collapsed:soc1        -0.052513   0.050885 326.444862
age_m:soc1                                   0.070232   0.049584 214.690888
ICPS_early_MOTOR_diff_collapsed:age_m:soc1  -0.038203   0.050708 367.774163
                                           t value Pr(>|t|)
(Intercept)                                  0.182   0.8558
ICPS_early_MOTOR_diff_collapsed             -0.861   0.3898
age_m                                       -0.251   0.8017
soc1                                         2.312   0.0218 *
sex1                                         0.027   0.9787
dp_inperson1                                -0.172   0.8636
ICPS_early_MOTOR_diff_collapsed:age_m        0.325   0.7452
ICPS_early_MOTOR_diff_collapsed:soc1        -1.032   0.3028
age_m:soc1                                   1.416   0.1581
ICPS_early_MOTOR_diff_collapsed:age_m:soc1  -0.753   0.4517
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
                 (Intr) ICPS_r_MOTOR__ age_m  soc1   sex1   dp_np1
ICPS_r_MOTOR__    0.050
age_m             0.030 -0.157
soc1             -0.033 -0.049          0.028
sex1             -0.003  0.065          0.008  0.005
dp_inpersn1      -0.721 -0.045         -0.051  0.018 -0.018
ICPS_r_MOTOR__:_ -0.177 -0.190         -0.009  0.024 -0.055  0.092
ICPS__MOTOR__:1   0.011 -0.020          0.047  0.026  0.045 -0.059
age_m:soc1        0.023  0.044         -0.013 -0.010 -0.032 -0.003
ICPS__MOTOR__:_:  0.018 -0.033         -0.085 -0.166  0.032 -0.004
                 ICPS_r_MOTOR__:_ ICPS__MOTOR__:1 ag_m:1
ICPS_r_MOTOR__
age_m
soc1
sex1
dp_inpersn1
ICPS_r_MOTOR__:_
ICPS__MOTOR__:1  -0.041
age_m:soc1       -0.089           -0.165
ICPS__MOTOR__:_:  0.072           -0.171          -0.006

Computing profile confidence intervals ...

## PES

In [38]:
label <- "PES"
model <- lmer(pes ~ ICPS_early_OCC_diff_collapsed * age_m  * soc + ICPS_early_DLPFC_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub), 
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Correlation matrix not shown by default, as p = 14 > 12.
Use print(obj, correlation=TRUE)  or
    vcov(obj)        if you need it

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula:
pes ~ ICPS_early_OCC_diff_collapsed * age_m * soc + ICPS_early_DLPFC_diff_collapsed *
    age_m * soc + sex + dp_inperson + (1 | sub)
   Data: tf_data

REML criterion at convergence: 1068.3

Scaled residuals:
     Min       1Q   Median       3Q      Max
-2.97938 -0.54771  0.03617  0.56810  2.48590

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.2665   0.5163
 Residual             0.6409   0.8005
Number of obs: 379, groups:  sub, 219

Fixed effects:
                                             Estimate Std. Error         df
(Intercept)                                 -0.022388   0.079479 213.149404
ICPS_early_OCC_diff_collapsed               -0.022186   0.050763 364.016894
age_m                                        0.078792   0.055661 207.919529
soc1                                        -0.023202   0.043106 189.134214
ICPS_early_DLPFC_diff_collapsed             -0.073346   0.051669 363.947844
sex1                                         0.236064   0.054733 199.169461
dp_inperson1                                 0.059459   0.079170 212.773323
ICPS_early_OCC_diff_collapsed:age_m         -0.076915   0.047592 362.256449
ICPS_early_OCC_diff_collapsed:soc1          -0.037466   0.047016 293.019145
age_m:soc1                                   0.113778   0.043449 191.149586
age_m:ICPS_early_DLPFC_diff_collapsed       -0.023815   0.049445 364.999848
soc1:ICPS_early_DLPFC_diff_collapsed        -0.005507   0.049508 322.513751
ICPS_early_OCC_diff_collapsed:age_m:soc1     0.058538   0.045996 328.154979
age_m:soc1:ICPS_early_DLPFC_diff_collapsed  -0.007608   0.047616 336.043961
                                           t value Pr(>|t|)
(Intercept)                                 -0.282  0.77846
ICPS_early_OCC_diff_collapsed               -0.437  0.66233
age_m                                        1.416  0.15840
soc1                                        -0.538  0.59104
ICPS_early_DLPFC_diff_collapsed             -1.420  0.15660
sex1                                         4.313 2.53e-05 ***
dp_inperson1                                 0.751  0.45346
ICPS_early_OCC_diff_collapsed:age_m         -1.616  0.10694
ICPS_early_OCC_diff_collapsed:soc1          -0.797  0.42616
age_m:soc1                                   2.619  0.00953 **
age_m:ICPS_early_DLPFC_diff_collapsed       -0.482  0.63034
soc1:ICPS_early_DLPFC_diff_collapsed        -0.111  0.91150
ICPS_early_OCC_diff_collapsed:age_m:soc1     1.273  0.20404
age_m:soc1:ICPS_early_DLPFC_diff_collapsed  -0.160  0.87316
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Computing profile confidence intervals ...

In [39]:
label <- "PES_motor"
plot_y <- "PES"
model <- lmer(pes ~ ICPS_early_MOTOR_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub), 
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula:
pes ~ ICPS_early_MOTOR_diff_collapsed * age_m * soc + sex + dp_inperson +
    (1 | sub)
   Data: tf_data

REML criterion at convergence: 1142.3

Scaled residuals:
     Min       1Q   Median       3Q      Max
-2.99023 -0.54866  0.05665  0.56788  3.04109

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.1796   0.4238
 Residual             0.7332   0.8562
Number of obs: 407, groups:  sub, 226

Fixed effects:
                                             Estimate Std. Error         df
(Intercept)                                 -0.059613   0.074934 219.877195
ICPS_early_MOTOR_diff_collapsed              0.036512   0.050574 373.963814
age_m                                        0.025630   0.052093 221.697835
soc1                                        -0.051484   0.043741 209.703941
sex1                                         0.233921   0.051566 213.948463
dp_inperson1                                 0.075153   0.074222 215.735640
ICPS_early_MOTOR_diff_collapsed:age_m       -0.005322   0.048873 392.357536
ICPS_early_MOTOR_diff_collapsed:soc1        -0.070988   0.046921 307.025029
age_m:soc1                                   0.120833   0.043908 213.917603
ICPS_early_MOTOR_diff_collapsed:age_m:soc1   0.070411   0.046420 346.043610
                                           t value Pr(>|t|)
(Intercept)                                 -0.796  0.42715
ICPS_early_MOTOR_diff_collapsed              0.722  0.47077
age_m                                        0.492  0.62320
soc1                                        -1.177  0.24052
sex1                                         4.536 9.54e-06 ***
dp_inperson1                                 1.013  0.31241
ICPS_early_MOTOR_diff_collapsed:age_m       -0.109  0.91334
ICPS_early_MOTOR_diff_collapsed:soc1        -1.513  0.13133
age_m:soc1                                   2.752  0.00643 **
ICPS_early_MOTOR_diff_collapsed:age_m:soc1   1.517  0.13022
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
                 (Intr) ICPS_r_MOTOR__ age_m  soc1   sex1   dp_np1
ICPS_r_MOTOR__    0.039
age_m             0.037 -0.163
soc1             -0.030 -0.052          0.036
sex1             -0.002  0.054          0.015 -0.003
dp_inpersn1      -0.720 -0.036         -0.054  0.019 -0.023
ICPS_r_MOTOR__:_ -0.165 -0.197          0.004  0.025 -0.061  0.076
ICPS__MOTOR__:1   0.002 -0.016          0.037  0.017  0.052 -0.042
age_m:soc1        0.029  0.043         -0.027 -0.001 -0.022 -0.003
ICPS__MOTOR__:_:  0.021 -0.027         -0.061 -0.181  0.029 -0.013
                 ICPS_r_MOTOR__:_ ICPS__MOTOR__:1 ag_m:1
ICPS_r_MOTOR__
age_m
soc1
sex1
dp_inpersn1
ICPS_r_MOTOR__:_
ICPS__MOTOR__:1  -0.030
age_m:soc1       -0.081           -0.184
ICPS__MOTOR__:_:  0.050           -0.152           0.013

Computing profile confidence intervals ...

# Updated DDM analyses

## Load data

In [2]:
rm(list = ls())
session = "s1_r1"
analysis_path = "/home/data/NDClab/analyses/thrive-theta-ddm/"
source(sprintf("%s/code/statistics/lmer_export_apa.R", analysis_path))
source(sprintf("%s/code/statistics/find_newest_file.R", analysis_path))
pic_path <- (sprintf("%s/derivatives/figs/%s", analysis_path, session))
# tf_data <- read.csv("/Users/fzaki001/IDENTIFIABLE/tf_data_collapsed_merged.csv")
tf_data <- read.csv(find_newest_file(sprintf("%s/derivatives/csv/%s/thrive*long*.csv", analysis_path, session)))
table_output_path = sprintf("%s/derivatives/statistics/full_sample/", analysis_path)

# it doesnt matter 0 or 1 because the models below use difference scores; because of that we need to get rid of duplicates (diff scores are the same for acc=0 and acc=1)
id_cols <- c('sub', 'age_m', 'sex', 'acc', 'soc', 'dp_inperson', 'first_soc')
data_cols <- c(
    'reversed_ratio_diff',
    'a_diff',
    'p_diff',
    'ter_diff',
    'ICPS_early_DLPFC_diff_collapsed',
    'ICPS_early_MOTOR_diff_collapsed',
    'ICPS_early_OCC_diff_collapsed'
)
tf_data <- tf_data[, c(id_cols, data_cols)]
tf_data <- tf_data %>%
  filter(!if_all(c(data_cols), is.na))
tf_data <- subset(tf_data, tf_data$acc == 1)

tf_data$sub <- as.factor(tf_data$sub)
tf_data$soc <- as.factor(tf_data$soc)
tf_data$sex <- as.factor(tf_data$sex)
tf_data$acc <- as.factor(tf_data$acc)
tf_data$first_soc <- as.factor(tf_data$first_soc)
# tf_data$task_num <- as.factor(tf_data$task_num)
tf_data$dp_inperson <- as.factor(tf_data$dp_inperson)

tf_data[c("age_m", data_cols)] <- as.data.frame(scale(tf_data[c("age_m", data_cols)]))

tf_data$soc <- revalue(tf_data$soc, c("0" = "NS", "1" = "S"))
tf_data$sex <- revalue(tf_data$sex, c("1" = "M", "2" = "F"))

# contrasts(tf_data$acc) <- rev(contr.sum(2))
contrasts(tf_data$sex) <- rev(contr.sum(2))
contrasts(tf_data$soc) <- rev(contr.sum(2))
contrasts(tf_data$first_soc) <- rev(contr.sum(2))
# contrasts(tf_data$task_num) <- rev(contr.sum(2))
contrasts(tf_data$dp_inperson) <- rev(contr.sum(2))

[1] "The newest file is: /home/data/NDClab/analyses/thrive-theta-ddm//derivatives/csv/s1_r1/thrive_long_s1_r1_01_02_2026_18_50_11.csv"

Warning message:
"There was 1 warning in `filter()`.
i In argument: `!if_all(c(data_cols), is.na)`.
Caused by warning:
! Using an external vector in selections was deprecated in tidyselect 1.1.0.
i Please use `all_of()` or `any_of()` instead.
  # Was:
  data %>% select(data_cols)

  # Now:
  data %>% select(all_of(data_cols))

See <https://tidyselect.r-lib.org/reference/faq-external-vector.html>."

## sda/rd (attentional ratio)

In [5]:
label <- "ratio_reversed_frontolateral"
plot_label <- bquote(atop("Attentional Control", sd[a] / r[d] ~ "(Post-error - Post-correct)"))
model <- lmer(reversed_ratio_diff ~ ICPS_early_DLPFC_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub),
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: reversed_ratio_diff ~ ICPS_early_DLPFC_diff_collapsed * age_m *
    soc + sex + dp_inperson + (1 | sub)
   Data: tf_data

REML criterion at convergence: 1060.7

Scaled residuals:
     Min       1Q   Median       3Q      Max
-2.54301 -0.56681  0.05757  0.53203  2.53325

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.1728   0.4157
 Residual             0.8702   0.9328
Number of obs: 360, groups:  sub, 213

Fixed effects:
                                             Estimate Std. Error         df
(Intercept)                                 -0.043459   0.084253 212.771194
ICPS_early_DLPFC_diff_collapsed              0.043162   0.060057 347.310941
age_m                                       -0.007254   0.059568 193.850229
soc1                                        -0.066001   0.050510 179.668538
sex1                                        -0.043750   0.057405 187.755648
dp_inperson1                                 0.052813   0.083675 211.637406
ICPS_early_DLPFC_diff_collapsed:age_m        0.017992   0.064979 349.646510
ICPS_early_DLPFC_diff_collapsed:soc1        -0.045436   0.058077 310.218801
age_m:soc1                                   0.013226   0.051981 183.094558
ICPS_early_DLPFC_diff_collapsed:age_m:soc1   0.036925   0.064135 330.892357
                                           t value Pr(>|t|)
(Intercept)                                 -0.516    0.607
ICPS_early_DLPFC_diff_collapsed              0.719    0.473
age_m                                       -0.122    0.903
soc1                                        -1.307    0.193
sex1                                        -0.762    0.447
dp_inperson1                                 0.631    0.529
ICPS_early_DLPFC_diff_collapsed:age_m        0.277    0.782
ICPS_early_DLPFC_diff_collapsed:soc1        -0.782    0.435
age_m:soc1                                   0.254    0.799
ICPS_early_DLPFC_diff_collapsed:age_m:soc1   0.576    0.565

Correlation of Fixed Effects:
                 (Intr) ICPS_r_DLPFC__ age_m  soc1   sex1   dp_np1
ICPS_r_DLPFC__    0.079
age_m             0.072 -0.096
soc1             -0.027  0.040         -0.001
sex1             -0.026 -0.048         -0.005 -0.005
dp_inpersn1      -0.727 -0.062         -0.079  0.008  0.000
ICPS_r_DLPFC__:_ -0.112 -0.196          0.014 -0.018 -0.001  0.041
ICPS__DLPFC__:1   0.076  0.047         -0.017  0.060 -0.001 -0.065
age_m:soc1        0.005 -0.030          0.007  0.026  0.006 -0.007
ICPS__DLPFC__:_:  0.037  0.110          0.090 -0.126  0.028 -0.060
                 ICPS_r_DLPFC__:_ ICPS__DLPFC__:1 ag_m:1
ICPS_r_DLPFC__
age_m
soc1
sex1
dp_inpersn1
ICPS_r_DLPFC__:_
ICPS__DLPFC__:1   0.102
age_m:soc1        0.082           -0.106
ICPS__DLPFC__:_:  0.078           -0.199           0.036

Computing profile confidence intervals ...

In [6]:
label <- "ratio_reversed_midlateral"
plot_label <- bquote(atop("Attentional Control", sd[a] / r[d] ~ "(Post-error - Post-correct)"))
model <- lmer(reversed_ratio_diff ~ ICPS_early_MOTOR_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub),
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: reversed_ratio_diff ~ ICPS_early_MOTOR_diff_collapsed * age_m *
    soc + sex + dp_inperson + (1 | sub)
   Data: tf_data

REML criterion at convergence: 1070.9

Scaled residuals:
     Min       1Q   Median       3Q      Max
-2.43515 -0.60592  0.02835  0.57791  2.56940

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.1570   0.3962
 Residual             0.8622   0.9286
Number of obs: 366, groups:  sub, 214

Fixed effects:
                                             Estimate Std. Error         df
(Intercept)                                -5.879e-02  8.170e-02  2.085e+02
ICPS_early_MOTOR_diff_collapsed             4.220e-02  5.880e-02  3.179e+02
age_m                                      -2.669e-02  5.811e-02  1.983e+02
soc1                                       -5.748e-02  5.008e-02  1.860e+02
sex1                                       -3.194e-02  5.626e-02  1.933e+02
dp_inperson1                                5.571e-02  8.085e-02  2.057e+02
ICPS_early_MOTOR_diff_collapsed:age_m       8.359e-02  5.931e-02  3.317e+02
ICPS_early_MOTOR_diff_collapsed:soc1        5.351e-02  5.494e-02  2.649e+02
age_m:soc1                                 -1.072e-03  5.124e-02  1.902e+02
ICPS_early_MOTOR_diff_collapsed:age_m:soc1 -8.175e-04  5.586e-02  2.892e+02
                                           t value Pr(>|t|)
(Intercept)                                 -0.720    0.473
ICPS_early_MOTOR_diff_collapsed              0.718    0.474
age_m                                       -0.459    0.647
soc1                                        -1.148    0.253
sex1                                        -0.568    0.571
dp_inperson1                                 0.689    0.492
ICPS_early_MOTOR_diff_collapsed:age_m        1.409    0.160
ICPS_early_MOTOR_diff_collapsed:soc1         0.974    0.331
age_m:soc1                                  -0.021    0.983
ICPS_early_MOTOR_diff_collapsed:age_m:soc1  -0.015    0.988

Correlation of Fixed Effects:
                 (Intr) ICPS_r_MOTOR__ age_m  soc1   sex1   dp_np1
ICPS_r_MOTOR__    0.071
age_m             0.052 -0.152
soc1             -0.057 -0.066          0.027
sex1             -0.002  0.069         -0.011  0.004
dp_inpersn1      -0.718 -0.084         -0.052  0.036 -0.011
ICPS_r_MOTOR__:_ -0.194 -0.179         -0.041  0.011 -0.043  0.115
ICPS__MOTOR__:1  -0.005 -0.084          0.025  0.017  0.057 -0.043
age_m:soc1        0.012  0.023         -0.017  0.029 -0.017  0.012
ICPS__MOTOR__:_:  0.013  0.029         -0.035 -0.168  0.010 -0.012
                 ICPS_r_MOTOR__:_ ICPS__MOTOR__:1 ag_m:1
ICPS_r_MOTOR__
age_m
soc1
sex1
dp_inpersn1
ICPS_r_MOTOR__:_
ICPS__MOTOR__:1   0.022
age_m:soc1       -0.048           -0.162
ICPS__MOTOR__:_:  0.062           -0.158          -0.035

Computing profile confidence intervals ...

In [7]:
label <- "ratio_reversed_posterolateral"
plot_label <- bquote(atop("Attentional Control", sd[a] / r[d] ~ "(Post-error - Post-correct)"))
model <- lmer(reversed_ratio_diff ~ ICPS_early_OCC_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub),
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: reversed_ratio_diff ~ ICPS_early_OCC_diff_collapsed * age_m *
    soc + sex + dp_inperson + (1 | sub)
   Data: tf_data

REML criterion at convergence: 1050.9

Scaled residuals:
     Min       1Q   Median       3Q      Max
-2.43674 -0.63031  0.04997  0.58130  2.58214

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.1392   0.3731
 Residual             0.8309   0.9115
Number of obs: 365, groups:  sub, 213

Fixed effects:
                                           Estimate Std. Error         df
(Intercept)                               -0.029941   0.077988 194.168513
ICPS_early_OCC_diff_collapsed              0.166999   0.056442 326.085882
age_m                                      0.016512   0.055784 183.984510
soc1                                      -0.049044   0.048682 176.659494
sex1                                      -0.027530   0.054754 184.916805
dp_inperson1                               0.056366   0.078079 194.554210
ICPS_early_OCC_diff_collapsed:age_m        0.030507   0.058317 345.823546
ICPS_early_OCC_diff_collapsed:soc1         0.059989   0.053527 277.340562
age_m:soc1                                 0.026543   0.049427 176.777928
ICPS_early_OCC_diff_collapsed:age_m:soc1  -0.008058   0.056163 303.113848
                                         t value Pr(>|t|)
(Intercept)                               -0.384  0.70146
ICPS_early_OCC_diff_collapsed              2.959  0.00331 **
age_m                                      0.296  0.76756
soc1                                      -1.007  0.31510
sex1                                      -0.503  0.61571
dp_inperson1                               0.722  0.47122
ICPS_early_OCC_diff_collapsed:age_m        0.523  0.60123
ICPS_early_OCC_diff_collapsed:soc1         1.121  0.26338
age_m:soc1                                 0.537  0.59194
ICPS_early_OCC_diff_collapsed:age_m:soc1  -0.143  0.88601
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
               (Intr) ICPS_r_OCC__ age_m  soc1   sex1   dp_np1 ICPS_r_OCC__:_
ICPS_r_OCC__    0.004
age_m           0.051 -0.020
soc1           -0.051  0.000        0.037
sex1           -0.011  0.068       -0.013  0.008
dp_inpersn1    -0.711  0.017       -0.064  0.014  0.012
ICPS_r_OCC__:_  0.039  0.008        0.060  0.102 -0.052 -0.070
ICPS__OCC__:1  -0.001 -0.066        0.089  0.020 -0.025  0.009 -0.012
age_m:soc1      0.012  0.103       -0.034  0.008  0.037  0.021 -0.012
ICPS__OCC__:_:  0.039 -0.011        0.007 -0.013  0.032  0.037 -0.009
               ICPS__OCC__:1 ag_m:1
ICPS_r_OCC__
age_m
soc1
sex1
dp_inpersn1
ICPS_r_OCC__:_
ICPS__OCC__:1
age_m:soc1     -0.018
ICPS__OCC__:_:  0.019         0.048

Computing profile confidence intervals ...

In [3]:
label <- "ratio_reversed_all_three"
plot_label <- bquote(atop("Attentional Control", sd[a] / r[d] ~ "(Post-error - Post-correct)"))
model <- lmer(reversed_ratio_diff ~ ICPS_early_OCC_diff_collapsed * age_m  * soc + ICPS_early_MOTOR_diff_collapsed * age_m * soc + ICPS_early_DLPFC_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub),
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Correlation matrix not shown by default, as p = 18 > 12.
Use print(obj, correlation=TRUE)  or
    vcov(obj)        if you need it

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: reversed_ratio_diff ~ ICPS_early_OCC_diff_collapsed * age_m *
    soc + ICPS_early_MOTOR_diff_collapsed * age_m * soc + ICPS_early_DLPFC_diff_collapsed *
    age_m * soc + sex + dp_inperson + (1 | sub)
   Data: tf_data

REML criterion at convergence: 1026.4

Scaled residuals:
    Min      1Q  Median      3Q     Max
-2.3709 -0.6152  0.0267  0.5501  2.5955

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.1092   0.3304
 Residual             0.8995   0.9484
Number of obs: 344, groups:  sub, 207

Fixed effects:
                                             Estimate Std. Error         df
(Intercept)                                 -0.064240   0.083338 193.636781
ICPS_early_OCC_diff_collapsed                0.167163   0.061823 309.840092
age_m                                       -0.011185   0.059845 177.328462
soc1                                        -0.052093   0.053431 167.917904
ICPS_early_MOTOR_diff_collapsed             -0.012166   0.072707 303.783986
ICPS_early_DLPFC_diff_collapsed             -0.025866   0.071907 325.280300
sex1                                        -0.023968   0.057465 174.790537
dp_inperson1                                 0.067286   0.082319 194.429333
ICPS_early_OCC_diff_collapsed:age_m         -0.009367   0.064384 322.128659
ICPS_early_OCC_diff_collapsed:soc1           0.040216   0.060111 283.968703
age_m:soc1                                  -0.005288   0.054878 169.525527
age_m:ICPS_early_MOTOR_diff_collapsed        0.079052   0.069845 309.829976
soc1:ICPS_early_MOTOR_diff_collapsed         0.120714   0.069701 266.617350
age_m:ICPS_early_DLPFC_diff_collapsed        0.006762   0.075416 325.965521
soc1:ICPS_early_DLPFC_diff_collapsed        -0.100043   0.070746 309.896067
ICPS_early_OCC_diff_collapsed:age_m:soc1    -0.040391   0.063230 302.410280
age_m:soc1:ICPS_early_MOTOR_diff_collapsed  -0.007895   0.067542 282.164100
age_m:soc1:ICPS_early_DLPFC_diff_collapsed   0.028212   0.074953 314.468395
                                           t value Pr(>|t|)
(Intercept)                                 -0.771  0.44174
ICPS_early_OCC_diff_collapsed                2.704  0.00723 **
age_m                                       -0.187  0.85195
soc1                                        -0.975  0.33098
ICPS_early_MOTOR_diff_collapsed             -0.167  0.86722
ICPS_early_DLPFC_diff_collapsed             -0.360  0.71929
sex1                                        -0.417  0.67713
dp_inperson1                                 0.817  0.41472
ICPS_early_OCC_diff_collapsed:age_m         -0.145  0.88442
ICPS_early_OCC_diff_collapsed:soc1           0.669  0.50403
age_m:soc1                                  -0.096  0.92335
age_m:ICPS_early_MOTOR_diff_collapsed        1.132  0.25858
soc1:ICPS_early_MOTOR_diff_collapsed         1.732  0.08445 .
age_m:ICPS_early_DLPFC_diff_collapsed        0.090  0.92861
soc1:ICPS_early_DLPFC_diff_collapsed        -1.414  0.15833
ICPS_early_OCC_diff_collapsed:age_m:soc1    -0.639  0.52344
age_m:soc1:ICPS_early_MOTOR_diff_collapsed  -0.117  0.90703
age_m:soc1:ICPS_early_DLPFC_diff_collapsed   0.376  0.70688
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Computing profile confidence intervals ...

## a (boundary separation)

In [31]:
label <- "boundary_frontolateral"
plot_label <- 'boundary separation'
model <- lmer(a_diff ~ ICPS_early_DLPFC_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub),
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula:
pea ~ ICPS_early_DLPFC_diff_collapsed * age_m * soc + sex + dp_inperson +
    (1 | sub)
   Data: tf_data

REML criterion at convergence: 1149.5

Scaled residuals:
     Min       1Q   Median       3Q      Max
-3.14453 -0.52595  0.03846  0.59730  2.74918

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.1465   0.3827
 Residual             0.8299   0.9110
Number of obs: 399, groups:  sub, 224

Fixed effects:
                                            Estimate Std. Error        df
(Intercept)                                 -0.07476    0.07811 216.77836
ICPS_early_DLPFC_diff_collapsed              0.02406    0.05169 386.09042
age_m                                        0.18166    0.05354 204.88817
soc1                                        -0.02942    0.04671 195.26470
sex1                                         0.03842    0.05266 197.53340
dp_inperson1                                 0.08262    0.07767 215.66770
ICPS_early_DLPFC_diff_collapsed:age_m       -0.04416    0.05053 387.77023
ICPS_early_DLPFC_diff_collapsed:soc1         0.03091    0.05023 349.36424
age_m:soc1                                   0.03156    0.04692 197.83711
ICPS_early_DLPFC_diff_collapsed:age_m:soc1  -0.04922    0.04944 358.55321
                                           t value Pr(>|t|)
(Intercept)                                 -0.957  0.33954
ICPS_early_DLPFC_diff_collapsed              0.465  0.64193
age_m                                        3.393  0.00083 ***
soc1                                        -0.630  0.52945
sex1                                         0.730  0.46656
dp_inperson1                                 1.064  0.28863
ICPS_early_DLPFC_diff_collapsed:age_m       -0.874  0.38272
ICPS_early_DLPFC_diff_collapsed:soc1         0.615  0.53867
age_m:soc1                                   0.673  0.50200
ICPS_early_DLPFC_diff_collapsed:age_m:soc1  -0.996  0.32008
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
                 (Intr) ICPS_r_DLPFC__ age_m  soc1   sex1   dp_np1
ICPS_r_DLPFC__    0.046
age_m             0.076 -0.126
soc1             -0.020  0.053          0.002
sex1             -0.028 -0.035          0.014 -0.012
dp_inpersn1      -0.732 -0.045         -0.082  0.019 -0.001
ICPS_r_DLPFC__:_ -0.116 -0.158         -0.070 -0.029  0.022  0.026
ICPS__DLPFC__:1   0.071  0.149         -0.031  0.029 -0.019 -0.045
age_m:soc1        0.017 -0.034          0.011  0.027  0.003 -0.018
ICPS__DLPFC__:_:  0.018 -0.029          0.035 -0.159  0.021 -0.052
                 ICPS_r_DLPFC__:_ ICPS__DLPFC__:1 ag_m:1
ICPS_r_DLPFC__
age_m
soc1
sex1
dp_inpersn1
ICPS_r_DLPFC__:_
ICPS__DLPFC__:1  -0.029
age_m:soc1        0.016           -0.143
ICPS__DLPFC__:_:  0.075           -0.179          -0.061

Computing profile confidence intervals ...

In [27]:
png(file=sprintf("%s/%s_stats_frontolateral_model_only.png", pic_path, label), width=9, height=5, units="in", res=600)
interact_plot(model, pred = "ICPS_early_DLPFC_diff_collapsed", modx = "age_m", interval = 1, dodge.width = 0.2,
              y.label = plot_label,
              x.label = "Midfrontal-Frontolateral ICPS (Error - Correct)",
              legend.main = "Age",
              plot.points = T) + 
  theme_minimal() +
  theme(
    text = element_text(size = 14), # Change the base font size
    axis.title = element_text(size = 16),                        # Change the axis title font size
    axis.text = element_text(size = 14),                         # Change the axis text font size
    # legend.text = element_text(size = 14),                       # Change the legend text font size
    # legend.title = element_text(size = 14),                     # Change the legend title font size
    plot.title = element_text(size = 18, face = "bold")         # Change the plot title font size and make it bold
  ) + theme(legend.position = "none") +
  scale_y_continuous(breaks = seq(-3, 3, by = 1)) +
  scale_x_continuous(breaks = seq(-3, 3, by = 1)) + theme(legend.position = "bottom")
dev.off()

agg_record_1088077279
                    2

In [9]:
label <- "boundary_midlateral"
plot_label <- bquote(atop("Attentional Control", sd[a] / r[d] ~ "(Post-error - Post-correct)"))
model <- lmer(a_diff ~ ICPS_early_MOTOR_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub),
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: a_diff ~ ICPS_early_MOTOR_diff_collapsed * age_m * soc + sex +
    dp_inperson + (1 | sub)
   Data: tf_data

REML criterion at convergence: 1056.4

Scaled residuals:
     Min       1Q   Median       3Q      Max
-2.74175 -0.64152 -0.01014  0.64604  2.64944

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.04712  0.2171
 Residual             0.95413  0.9768
Number of obs: 362, groups:  sub, 212

Fixed effects:
                                            Estimate Std. Error        df
(Intercept)                                 -0.01668    0.07946 203.51163
ICPS_early_MOTOR_diff_collapsed              0.02076    0.05770 295.71571
age_m                                        0.10671    0.05567 189.96732
soc1                                        -0.03466    0.05249 186.74996
sex1                                         0.12530    0.05393 187.23521
dp_inperson1                                 0.04523    0.07856 201.13395
ICPS_early_MOTOR_diff_collapsed:age_m       -0.10221    0.05824 313.24882
ICPS_early_MOTOR_diff_collapsed:soc1        -0.04857    0.05636 278.74869
age_m:soc1                                   0.03524    0.05352 188.84173
ICPS_early_MOTOR_diff_collapsed:age_m:soc1   0.05141    0.05683 299.29089
                                           t value Pr(>|t|)
(Intercept)                                 -0.210   0.8340
ICPS_early_MOTOR_diff_collapsed              0.360   0.7193
age_m                                        1.917   0.0568 .
soc1                                        -0.660   0.5098
sex1                                         2.323   0.0212 *
dp_inperson1                                 0.576   0.5654
ICPS_early_MOTOR_diff_collapsed:age_m       -1.755   0.0802 .
ICPS_early_MOTOR_diff_collapsed:soc1        -0.862   0.3896
age_m:soc1                                   0.658   0.5110
ICPS_early_MOTOR_diff_collapsed:age_m:soc1   0.905   0.3664
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
                 (Intr) ICPS_r_MOTOR__ age_m  soc1   sex1   dp_np1
ICPS_r_MOTOR__    0.066
age_m             0.051 -0.157
soc1             -0.046 -0.068          0.040
sex1             -0.003  0.084         -0.016 -0.007
dp_inpersn1      -0.727 -0.074         -0.057  0.021  0.000
ICPS_r_MOTOR__:_ -0.203 -0.177         -0.040  0.011 -0.039  0.123
ICPS__MOTOR__:1  -0.016 -0.083          0.028  0.018  0.056 -0.038
age_m:soc1        0.016  0.024         -0.024  0.016 -0.015  0.017
ICPS__MOTOR__:_:  0.014  0.031         -0.040 -0.169  0.006 -0.011
                 ICPS_r_MOTOR__:_ ICPS__MOTOR__:1 ag_m:1
ICPS_r_MOTOR__
age_m
soc1
sex1
dp_inpersn1
ICPS_r_MOTOR__:_
ICPS__MOTOR__:1   0.024
age_m:soc1       -0.042           -0.164
ICPS__MOTOR__:_:  0.062           -0.163          -0.035

Computing profile confidence intervals ...

In [10]:
label <- "boundary_posterolateral"
plot_label <- bquote(atop("Attentional Control", sd[a] / r[d] ~ "(Post-error - Post-correct)"))
model <- lmer(a_diff ~ ICPS_early_OCC_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub),
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: a_diff ~ ICPS_early_OCC_diff_collapsed * age_m * soc + sex +
    dp_inperson + (1 | sub)
   Data: tf_data

REML criterion at convergence: 1042.4

Scaled residuals:
     Min       1Q   Median       3Q      Max
-2.74633 -0.64997 -0.03642  0.64555  2.59190

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.02805  0.1675
 Residual             0.94136  0.9702
Number of obs: 361, groups:  sub, 211

Fixed effects:
                                           Estimate Std. Error         df
(Intercept)                               -0.037514   0.076146 191.084811
ICPS_early_OCC_diff_collapsed              0.071889   0.055943 306.949489
age_m                                      0.103927   0.053573 177.231937
soc1                                      -0.004811   0.051572 179.445257
sex1                                       0.144133   0.052680 180.074088
dp_inperson1                               0.066013   0.076309 192.139433
ICPS_early_OCC_diff_collapsed:age_m        0.051679   0.058104 327.781694
ICPS_early_OCC_diff_collapsed:soc1        -0.031913   0.055301 297.741150
age_m:soc1                                 0.058716   0.052221 177.304549
ICPS_early_OCC_diff_collapsed:age_m:soc1  -0.037009   0.057556 319.853191
                                         t value Pr(>|t|)
(Intercept)                               -0.493  0.62281
ICPS_early_OCC_diff_collapsed              1.285  0.19975
age_m                                      1.940  0.05398 .
soc1                                      -0.093  0.92577
sex1                                       2.736  0.00684 **
dp_inperson1                               0.865  0.38808
ICPS_early_OCC_diff_collapsed:age_m        0.889  0.37443
ICPS_early_OCC_diff_collapsed:soc1        -0.577  0.56432
age_m:soc1                                 1.124  0.26238
ICPS_early_OCC_diff_collapsed:age_m:soc1  -0.643  0.52068
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
               (Intr) ICPS_r_OCC__ age_m  soc1   sex1   dp_np1 ICPS_r_OCC__:_
ICPS_r_OCC__   -0.006
age_m           0.047 -0.015
soc1           -0.041  0.006        0.047
sex1           -0.011  0.066       -0.017 -0.002
dp_inpersn1    -0.720  0.023       -0.067 -0.001  0.022
ICPS_r_OCC__:_  0.044  0.003        0.044  0.096 -0.045 -0.072
ICPS__OCC__:1  -0.008 -0.064        0.090  0.014 -0.032  0.018 -0.008
age_m:soc1      0.015  0.096       -0.039 -0.002  0.037  0.025  0.009
ICPS__OCC__:_:  0.039 -0.005        0.012 -0.010  0.028  0.037 -0.015
               ICPS__OCC__:1 ag_m:1
ICPS_r_OCC__
age_m
soc1
sex1
dp_inpersn1
ICPS_r_OCC__:_
ICPS__OCC__:1
age_m:soc1     -0.014
ICPS__OCC__:_:  0.008         0.040

Computing profile confidence intervals ...

In [4]:
label <- "boundary_all_three"
plot_label <- 'boundary separation'
model <- lmer(a_diff ~ ICPS_early_OCC_diff_collapsed * age_m  * soc + ICPS_early_MOTOR_diff_collapsed * age_m * soc + ICPS_early_DLPFC_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub),
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Correlation matrix not shown by default, as p = 18 > 12.
Use print(obj, correlation=TRUE)  or
    vcov(obj)        if you need it

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula:
a_diff ~ ICPS_early_OCC_diff_collapsed * age_m * soc + ICPS_early_MOTOR_diff_collapsed *
    age_m * soc + ICPS_early_DLPFC_diff_collapsed * age_m * soc +
    sex + dp_inperson + (1 | sub)
   Data: tf_data

REML criterion at convergence: 1003.4

Scaled residuals:
     Min       1Q   Median       3Q      Max
-2.77903 -0.63181 -0.04632  0.66306  2.49593

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.05292  0.2300
 Residual             0.91714  0.9577
Number of obs: 340, groups:  sub, 205

Fixed effects:
                                             Estimate Std. Error         df
(Intercept)                                  0.025425   0.081776 190.971682
ICPS_early_OCC_diff_collapsed                0.106733   0.060734 302.728945
age_m                                        0.110524   0.057779 171.009499
soc1                                         0.010373   0.053952 167.362686
ICPS_early_MOTOR_diff_collapsed             -0.024208   0.071363 292.252212
ICPS_early_DLPFC_diff_collapsed              0.023484   0.071262 320.171703
sex1                                         0.129111   0.055626 170.415287
dp_inperson1                                 0.023626   0.080842 192.955227
ICPS_early_OCC_diff_collapsed:age_m          0.092825   0.063255 314.808109
ICPS_early_OCC_diff_collapsed:soc1           0.007497   0.059959 290.851637
age_m:soc1                                   0.059078   0.055194 167.350090
age_m:ICPS_early_MOTOR_diff_collapsed       -0.083182   0.068510 299.124841
soc1:ICPS_early_MOTOR_diff_collapsed        -0.067767   0.069470 270.889364
age_m:ICPS_early_DLPFC_diff_collapsed       -0.150424   0.074901 321.332100
soc1:ICPS_early_DLPFC_diff_collapsed         0.061243   0.070614 313.694916
ICPS_early_OCC_diff_collapsed:age_m:soc1    -0.027658   0.062613 305.293077
age_m:soc1:ICPS_early_MOTOR_diff_collapsed   0.055850   0.067120 283.301445
age_m:soc1:ICPS_early_DLPFC_diff_collapsed  -0.088466   0.074825 315.778299
                                           t value Pr(>|t|)
(Intercept)                                  0.311   0.7562
ICPS_early_OCC_diff_collapsed                1.757   0.0799 .
age_m                                        1.913   0.0574 .
soc1                                         0.192   0.8478
ICPS_early_MOTOR_diff_collapsed             -0.339   0.7347
ICPS_early_DLPFC_diff_collapsed              0.330   0.7420
sex1                                         2.321   0.0215 *
dp_inperson1                                 0.292   0.7704
ICPS_early_OCC_diff_collapsed:age_m          1.467   0.1432
ICPS_early_OCC_diff_collapsed:soc1           0.125   0.9006
age_m:soc1                                   1.070   0.2860
age_m:ICPS_early_MOTOR_diff_collapsed       -1.214   0.2256
soc1:ICPS_early_MOTOR_diff_collapsed        -0.975   0.3302
age_m:ICPS_early_DLPFC_diff_collapsed       -2.008   0.0454 *
soc1:ICPS_early_DLPFC_diff_collapsed         0.867   0.3864
ICPS_early_OCC_diff_collapsed:age_m:soc1    -0.442   0.6590
age_m:soc1:ICPS_early_MOTOR_diff_collapsed   0.832   0.4061
age_m:soc1:ICPS_early_DLPFC_diff_collapsed  -1.182   0.2380
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Computing profile confidence intervals ...

In [29]:
png(file=sprintf("%s/%s_stats_all_three.png", pic_path, label), width=9, height=5, units="in", res=600)
interact_plot(model, pred = "ICPS_early_DLPFC_diff_collapsed", modx = "age_m", interval = 1, dodge.width = 0.2,
              y.label = plot_label,
              x.label = "Midfrontal-Frontolateral ICPS (Error - Correct)",
              legend.main = "Age",
              plot.points = T) + 
  theme_minimal() +
  theme(
    text = element_text(size = 14), # Change the base font size
    axis.title = element_text(size = 16),                        # Change the axis title font size
    axis.text = element_text(size = 14),                         # Change the axis text font size
    # legend.text = element_text(size = 14),                       # Change the legend text font size
    # legend.title = element_text(size = 14),                     # Change the legend title font size
    plot.title = element_text(size = 18, face = "bold")         # Change the plot title font size and make it bold
  ) + theme(legend.position = "none") +
  scale_y_continuous(breaks = seq(-3, 3, by = 1)) +
  scale_x_continuous(breaks = seq(-3, 3, by = 1)) + theme(legend.position = "bottom")
dev.off()

agg_record_52148715
                  2

In [5]:
library(emmeans)

# 1. Directly specify the standardized values (-1 SD, Mean, +1 SD)
age_points <- list(age_m = c(-1, 0, 1))

# 2. Compute the simple slopes
slopes <- emtrends(model, 
                   specs = ~ age_m, 
                   var = "ICPS_early_DLPFC_diff_collapsed", 
                   at = age_points)

# 3. View the slopes with 95% Confidence Intervals and p-values
summary(slopes, infer = c(TRUE, TRUE))

Cannot use mode = "kenward-roger" because *pbkrtest* package is not installed

NOTE: Results may be misleading due to involvement in interactions

  age_m ICPS_early_DLPFC_diff_collapsed.trend SE         df       lower.CL
1 -1     0.17390826                           0.11321865 321.9372 -0.0488336
2  0     0.02348432                           0.07126169 320.1717 -0.1167160
3  1    -0.12693962                           0.09251097 316.7672 -0.3089532
  upper.CL   t.ratio    p.value
1 0.39665011  1.5360389 0.1255110
2 0.16368463  0.3295504 0.7419552
3 0.05507398 -1.3721574 0.1709853

In [6]:
library(emmeans)

# 1. Compute the slopes at the standardized age points
age_points <- list(age_m = c(-1, 0, 1))
slopes <- emtrends(model, 
                   specs = ~ age_m, 
                   var = "ICPS_early_DLPFC_diff_collapsed", 
                   at = age_points)

# 2. Compute paired comparisons between the slopes
pairwise_diffs <- pairs(slopes)

# 3. View the results
summary(pairwise_diffs, infer = c(TRUE, TRUE))

Cannot use mode = "kenward-roger" because *pbkrtest* package is not installed

NOTE: Results may be misleading due to involvement in interactions

  contrast           estimate  SE         df       lower.CL    upper.CL
1 (age_m-1) - age_m0 0.1504239 0.07490089 321.3321 -0.02593965 0.3267875
2 (age_m-1) - age_m1 0.3008479 0.14980179 321.3321 -0.05187930 0.6535751
3 age_m0 - age_m1    0.1504239 0.07490089 321.3321 -0.02593965 0.3267875
  t.ratio  p.value
1 2.008306 0.1118253
2 2.008306 0.1118253
3 2.008306 0.1118253

# Updated raw behav measures

## Load data

In [30]:
rm(list = ls())
session = "s1_r1"
analysis_path = "/home/data/NDClab/analyses/thrive-theta-ddm/"
source(sprintf("%s/code/statistics/lmer_export_apa.R", analysis_path))
source(sprintf("%s/code/statistics/find_newest_file.R", analysis_path))
pic_path <- (sprintf("%s/derivatives/figs/%s", analysis_path, session))
# tf_data <- read.csv("/Users/fzaki001/IDENTIFIABLE/tf_data_collapsed_merged.csv")
tf_data <- read.csv(find_newest_file(sprintf("%s/derivatives/csv/%s/thrive*long*.csv", analysis_path, session)))
table_output_path = sprintf("%s/derivatives/statistics/full_sample/", analysis_path)

# it doesnt matter 0 or 1 because the models below use difference scores; because of that we need to get rid of duplicates (diff scores are the same for acc=0 and acc=1)
id_cols <- c('sub', 'age_m', 'sex', 'acc', 'soc', 'dp_inperson', 'first_soc')
data_cols <- c(
    'pea',
    'peri_rt',
    'pes',
    'ICPS_early_DLPFC_diff_collapsed',
    'ICPS_early_MOTOR_diff_collapsed',
    'ICPS_early_OCC_diff_collapsed'
)
tf_data <- tf_data[, c(id_cols, data_cols)]
tf_data <- tf_data %>%
  filter(!if_all(c(data_cols), is.na))
tf_data <- subset(tf_data, tf_data$acc == 1)

tf_data$sub <- as.factor(tf_data$sub)
tf_data$soc <- as.factor(tf_data$soc)
tf_data$sex <- as.factor(tf_data$sex)
tf_data$acc <- as.factor(tf_data$acc)
tf_data$first_soc <- as.factor(tf_data$first_soc)
# tf_data$task_num <- as.factor(tf_data$task_num)
tf_data$dp_inperson <- as.factor(tf_data$dp_inperson)

tf_data[c("age_m", data_cols)] <- as.data.frame(scale(tf_data[c("age_m", data_cols)]))

tf_data$soc <- revalue(tf_data$soc, c("0" = "NS", "1" = "S"))
tf_data$sex <- revalue(tf_data$sex, c("1" = "M", "2" = "F"))
# tf_data$acc <- revalue(tf_data$acc, c("0" = "Error", "1" = "Correct"))

# contrasts(tf_data$acc) <- rev(contr.sum(2))
contrasts(tf_data$sex) <- rev(contr.sum(2))
contrasts(tf_data$soc) <- rev(contr.sum(2))
contrasts(tf_data$first_soc) <- rev(contr.sum(2))
# contrasts(tf_data$task_num) <- rev(contr.sum(2))
contrasts(tf_data$dp_inperson) <- rev(contr.sum(2))

[1] "The newest file is: /home/data/NDClab/analyses/thrive-theta-ddm//derivatives/csv/s1_r1/thrive_long_s1_r1_01_02_2026_18_50_11.csv"

## PEA

In [33]:
label <- "pea_frontolateral"
plot_label <- 'PEA'
model <- lmer(pea ~ ICPS_early_DLPFC_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub),
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula:
pea ~ ICPS_early_DLPFC_diff_collapsed * age_m * soc + sex + dp_inperson +
    (1 | sub)
   Data: tf_data

REML criterion at convergence: 1149.5

Scaled residuals:
     Min       1Q   Median       3Q      Max
-3.14453 -0.52595  0.03846  0.59730  2.74918

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.1465   0.3827
 Residual             0.8299   0.9110
Number of obs: 399, groups:  sub, 224

Fixed effects:
                                            Estimate Std. Error        df
(Intercept)                                 -0.07476    0.07811 216.77836
ICPS_early_DLPFC_diff_collapsed              0.02406    0.05169 386.09042
age_m                                        0.18166    0.05354 204.88817
soc1                                        -0.02942    0.04671 195.26470
sex1                                         0.03842    0.05266 197.53340
dp_inperson1                                 0.08262    0.07767 215.66770
ICPS_early_DLPFC_diff_collapsed:age_m       -0.04416    0.05053 387.77023
ICPS_early_DLPFC_diff_collapsed:soc1         0.03091    0.05023 349.36424
age_m:soc1                                   0.03156    0.04692 197.83711
ICPS_early_DLPFC_diff_collapsed:age_m:soc1  -0.04922    0.04944 358.55321
                                           t value Pr(>|t|)
(Intercept)                                 -0.957  0.33954
ICPS_early_DLPFC_diff_collapsed              0.465  0.64193
age_m                                        3.393  0.00083 ***
soc1                                        -0.630  0.52945
sex1                                         0.730  0.46656
dp_inperson1                                 1.064  0.28863
ICPS_early_DLPFC_diff_collapsed:age_m       -0.874  0.38272
ICPS_early_DLPFC_diff_collapsed:soc1         0.615  0.53867
age_m:soc1                                   0.673  0.50200
ICPS_early_DLPFC_diff_collapsed:age_m:soc1  -0.996  0.32008
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
                 (Intr) ICPS_r_DLPFC__ age_m  soc1   sex1   dp_np1
ICPS_r_DLPFC__    0.046
age_m             0.076 -0.126
soc1             -0.020  0.053          0.002
sex1             -0.028 -0.035          0.014 -0.012
dp_inpersn1      -0.732 -0.045         -0.082  0.019 -0.001
ICPS_r_DLPFC__:_ -0.116 -0.158         -0.070 -0.029  0.022  0.026
ICPS__DLPFC__:1   0.071  0.149         -0.031  0.029 -0.019 -0.045
age_m:soc1        0.017 -0.034          0.011  0.027  0.003 -0.018
ICPS__DLPFC__:_:  0.018 -0.029          0.035 -0.159  0.021 -0.052
                 ICPS_r_DLPFC__:_ ICPS__DLPFC__:1 ag_m:1
ICPS_r_DLPFC__
age_m
soc1
sex1
dp_inpersn1
ICPS_r_DLPFC__:_
ICPS__DLPFC__:1  -0.029
age_m:soc1        0.016           -0.143
ICPS__DLPFC__:_:  0.075           -0.179          -0.061

Computing profile confidence intervals ...

In [34]:
label <- "pea_midlateral"
plot_label <- 'PEA'
model <- lmer(pea ~ ICPS_early_MOTOR_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub),
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula:
pea ~ ICPS_early_MOTOR_diff_collapsed * age_m * soc + sex + dp_inperson +
    (1 | sub)
   Data: tf_data

REML criterion at convergence: 1166.2

Scaled residuals:
    Min      1Q  Median      3Q     Max
-3.2075 -0.5255  0.0365  0.6085  2.7822

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.1598   0.3998
 Residual             0.8044   0.8969
Number of obs: 407, groups:  sub, 225

Fixed effects:
                                             Estimate Std. Error         df
(Intercept)                                 -0.055345   0.075926 214.446803
ICPS_early_MOTOR_diff_collapsed              0.071772   0.051367 369.617960
age_m                                        0.162430   0.053000 218.871281
soc1                                        -0.035989   0.045719 208.137355
sex1                                         0.048018   0.052437 210.777741
dp_inperson1                                 0.069584   0.075135 210.544342
ICPS_early_MOTOR_diff_collapsed:age_m       -0.028416   0.049957 390.813943
ICPS_early_MOTOR_diff_collapsed:soc1         0.049719   0.048246 311.163513
age_m:soc1                                   0.004395   0.045891 213.011290
ICPS_early_MOTOR_diff_collapsed:age_m:soc1  -0.019612   0.047777 351.293392
                                           t value Pr(>|t|)
(Intercept)                                 -0.729  0.46684
ICPS_early_MOTOR_diff_collapsed              1.397  0.16318
age_m                                        3.065  0.00245 **
soc1                                        -0.787  0.43208
sex1                                         0.916  0.36086
dp_inperson1                                 0.926  0.35544
ICPS_early_MOTOR_diff_collapsed:age_m       -0.569  0.56981
ICPS_early_MOTOR_diff_collapsed:soc1         1.031  0.30357
age_m:soc1                                   0.096  0.92380
ICPS_early_MOTOR_diff_collapsed:age_m:soc1  -0.411  0.68169
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
                 (Intr) ICPS_r_MOTOR__ age_m  soc1   sex1   dp_np1
ICPS_r_MOTOR__    0.053
age_m             0.039 -0.165
soc1             -0.034 -0.045          0.038
sex1             -0.001  0.060          0.018  0.000
dp_inpersn1      -0.717 -0.048         -0.054  0.021 -0.017
ICPS_r_MOTOR__:_ -0.179 -0.184          0.005  0.019 -0.064  0.089
ICPS__MOTOR__:1   0.014 -0.038          0.036  0.027  0.056 -0.053
age_m:soc1        0.032  0.038         -0.026  0.000 -0.018 -0.005
ICPS__MOTOR__:_:  0.012 -0.006         -0.061 -0.184  0.024 -0.002
                 ICPS_r_MOTOR__:_ ICPS__MOTOR__:1 ag_m:1
ICPS_r_MOTOR__
age_m
soc1
sex1
dp_inpersn1
ICPS_r_MOTOR__:_
ICPS__MOTOR__:1  -0.012
age_m:soc1       -0.077           -0.185
ICPS__MOTOR__:_:  0.035           -0.145           0.016

Computing profile confidence intervals ...

In [35]:
label <- "pea_posterolateral"
plot_label <- 'PEA'
model <- lmer(pea ~ ICPS_early_OCC_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub),
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula:
pea ~ ICPS_early_OCC_diff_collapsed * age_m * soc + sex + dp_inperson +
    (1 | sub)
   Data: tf_data

REML criterion at convergence: 1127

Scaled residuals:
    Min      1Q  Median      3Q     Max
-3.5958 -0.5665  0.0732  0.6211  2.4881

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.1172   0.3424
 Residual             0.8076   0.8987
Number of obs: 398, groups:  sub, 222

Fixed effects:
                                          Estimate Std. Error        df t value
(Intercept)                               -0.06954    0.07240 200.92345  -0.960
ICPS_early_OCC_diff_collapsed              0.10114    0.04969 368.11030   2.036
age_m                                      0.16606    0.05137 210.73889   3.233
soc1                                      -0.05072    0.04593 199.79856  -1.104
sex1                                       0.05216    0.05099 203.33214   1.023
dp_inperson1                               0.07282    0.07230 200.50821   1.007
ICPS_early_OCC_diff_collapsed:age_m        0.09023    0.04755 387.48522   1.897
ICPS_early_OCC_diff_collapsed:soc1         0.04417    0.04780 329.03719   0.924
age_m:soc1                                 0.04499    0.04605 206.20357   0.977
ICPS_early_OCC_diff_collapsed:age_m:soc1  -0.04325    0.04679 370.72114  -0.924
                                         Pr(>|t|)
(Intercept)                               0.33799
ICPS_early_OCC_diff_collapsed             0.04251 *
age_m                                     0.00142 **
soc1                                      0.27078
sex1                                      0.30749
dp_inperson1                              0.31504
ICPS_early_OCC_diff_collapsed:age_m       0.05851 .
ICPS_early_OCC_diff_collapsed:soc1        0.35623
age_m:soc1                                0.32978
ICPS_early_OCC_diff_collapsed:age_m:soc1  0.35590
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
               (Intr) ICPS_r_OCC__ age_m  soc1   sex1   dp_np1 ICPS_r_OCC__:_
ICPS_r_OCC__   -0.008
age_m           0.044  0.000
soc1           -0.028  0.006        0.039
sex1           -0.016  0.040        0.012  0.004
dp_inpersn1    -0.705  0.020       -0.057  0.007  0.000
ICPS_r_OCC__:_  0.022 -0.038        0.014  0.145 -0.053 -0.043
ICPS__OCC__:1  -0.004 -0.024        0.137  0.012 -0.037  0.015  0.090
age_m:soc1      0.028  0.152       -0.035  0.004  0.026  0.000  0.033
ICPS__OCC__:_:  0.071  0.094        0.041 -0.018  0.031  0.035 -0.115
               ICPS__OCC__:1 ag_m:1
ICPS_r_OCC__
age_m
soc1
sex1
dp_inpersn1
ICPS_r_OCC__:_
ICPS__OCC__:1
age_m:soc1     -0.006
ICPS__OCC__:_: -0.017         0.010

Computing profile confidence intervals ...

In [36]:
label <- "pea_all_three"
plot_label <- 'PEA'
model <- lmer(pea ~ ICPS_early_OCC_diff_collapsed * age_m  * soc + ICPS_early_MOTOR_diff_collapsed * age_m * soc + ICPS_early_DLPFC_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub),
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Correlation matrix not shown by default, as p = 18 > 12.
Use print(obj, correlation=TRUE)  or
    vcov(obj)        if you need it

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula:
pea ~ ICPS_early_OCC_diff_collapsed * age_m * soc + ICPS_early_MOTOR_diff_collapsed *
    age_m * soc + ICPS_early_DLPFC_diff_collapsed * age_m * soc +
    sex + dp_inperson + (1 | sub)
   Data: tf_data

REML criterion at convergence: 1083.9

Scaled residuals:
    Min      1Q  Median      3Q     Max
-3.5095 -0.5179  0.0762  0.5733  2.4774

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.1029   0.3208
 Residual             0.8351   0.9138
Number of obs: 372, groups:  sub, 216

Fixed effects:
                                             Estimate Std. Error         df
(Intercept)                                 -0.083351   0.077675 199.710114
ICPS_early_OCC_diff_collapsed                0.108243   0.054289 345.715197
age_m                                        0.162057   0.054710 196.318137
soc1                                        -0.035146   0.049634 184.662186
ICPS_early_MOTOR_diff_collapsed              0.019927   0.063861 334.420187
ICPS_early_DLPFC_diff_collapsed             -0.030000   0.060159 352.160139
sex1                                         0.072643   0.053225 186.046406
dp_inperson1                                 0.080089   0.076443 198.919614
ICPS_early_OCC_diff_collapsed:age_m          0.072946   0.050819 353.848770
ICPS_early_OCC_diff_collapsed:soc1           0.027804   0.053077 319.932172
age_m:soc1                                   0.035681   0.050041 189.130779
age_m:ICPS_early_MOTOR_diff_collapsed        0.010779   0.060048 341.913606
soc1:ICPS_early_MOTOR_diff_collapsed         0.059747   0.061448 297.653504
age_m:ICPS_early_DLPFC_diff_collapsed       -0.009393   0.056049 353.226847
soc1:ICPS_early_DLPFC_diff_collapsed         0.021317   0.059103 336.646947
ICPS_early_OCC_diff_collapsed:age_m:soc1    -0.046964   0.050501 348.044873
age_m:soc1:ICPS_early_MOTOR_diff_collapsed  -0.027943   0.058084 316.534726
age_m:soc1:ICPS_early_DLPFC_diff_collapsed  -0.016102   0.055647 347.198225
                                           t value Pr(>|t|)
(Intercept)                                 -1.073  0.28453
ICPS_early_OCC_diff_collapsed                1.994  0.04695 *
age_m                                        2.962  0.00343 **
soc1                                        -0.708  0.47977
ICPS_early_MOTOR_diff_collapsed              0.312  0.75521
ICPS_early_DLPFC_diff_collapsed             -0.499  0.61832
sex1                                         1.365  0.17395
dp_inperson1                                 1.048  0.29605
ICPS_early_OCC_diff_collapsed:age_m          1.435  0.15206
ICPS_early_OCC_diff_collapsed:soc1           0.524  0.60076
age_m:soc1                                   0.713  0.47670
age_m:ICPS_early_MOTOR_diff_collapsed        0.180  0.85765
soc1:ICPS_early_MOTOR_diff_collapsed         0.972  0.33168
age_m:ICPS_early_DLPFC_diff_collapsed       -0.168  0.86700
soc1:ICPS_early_DLPFC_diff_collapsed         0.361  0.71857
ICPS_early_OCC_diff_collapsed:age_m:soc1    -0.930  0.35304
age_m:soc1:ICPS_early_MOTOR_diff_collapsed  -0.481  0.63079
age_m:soc1:ICPS_early_DLPFC_diff_collapsed  -0.289  0.77247
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Computing profile confidence intervals ...

## PERI

In [37]:
label <- "peri_frontolateral"
plot_label <- 'PERI'
model <- lmer(peri_rt ~ ICPS_early_DLPFC_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub),
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: peri_rt ~ ICPS_early_DLPFC_diff_collapsed * age_m * soc + sex +
    dp_inperson + (1 | sub)
   Data: tf_data

REML criterion at convergence: 1161.8

Scaled residuals:
    Min      1Q  Median      3Q     Max
-3.3451 -0.5208 -0.0038  0.5702  2.9370

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.09447  0.3074
 Residual             0.91459  0.9563
Number of obs: 398, groups:  sub, 225

Fixed effects:
                                             Estimate Std. Error         df
(Intercept)                                  0.013601   0.078577 226.357971
ICPS_early_DLPFC_diff_collapsed              0.030113   0.053158 380.750425
age_m                                       -0.031146   0.053579 211.831720
soc1                                         0.105635   0.049020 204.663171
sex1                                        -0.006591   0.052418 203.226486
dp_inperson1                                -0.025854   0.077981 224.473593
ICPS_early_DLPFC_diff_collapsed:age_m        0.020581   0.052162 383.279759
ICPS_early_DLPFC_diff_collapsed:soc1        -0.014176   0.052201 358.385280
age_m:soc1                                   0.077006   0.049394 207.877041
ICPS_early_DLPFC_diff_collapsed:age_m:soc1   0.035383   0.051388 365.116230
                                           t value Pr(>|t|)
(Intercept)                                  0.173   0.8627
ICPS_early_DLPFC_diff_collapsed              0.566   0.5714
age_m                                       -0.581   0.5617
soc1                                         2.155   0.0323 *
sex1                                        -0.126   0.9001
dp_inperson1                                -0.332   0.7405
ICPS_early_DLPFC_diff_collapsed:age_m        0.395   0.6934
ICPS_early_DLPFC_diff_collapsed:soc1        -0.272   0.7861
age_m:soc1                                   1.559   0.1205
ICPS_early_DLPFC_diff_collapsed:age_m:soc1   0.689   0.4915
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
                 (Intr) ICPS_r_DLPFC__ age_m  soc1   sex1   dp_np1
ICPS_r_DLPFC__    0.068
age_m             0.063 -0.141
soc1             -0.011  0.063         -0.013
sex1             -0.028 -0.023          0.007 -0.003
dp_inpersn1      -0.736 -0.052         -0.076  0.009 -0.006
ICPS_r_DLPFC__:_ -0.133 -0.186         -0.047 -0.046  0.013  0.036
ICPS__DLPFC__:1   0.085  0.165         -0.046  0.053 -0.010 -0.056
age_m:soc1        0.000 -0.052          0.020  0.011 -0.008 -0.011
ICPS__DLPFC__:_:  0.001 -0.058          0.049 -0.167  0.016 -0.042
                 ICPS_r_DLPFC__:_ ICPS__DLPFC__:1 ag_m:1
ICPS_r_DLPFC__
age_m
soc1
sex1
dp_inpersn1
ICPS_r_DLPFC__:_
ICPS__DLPFC__:1  -0.060
age_m:soc1        0.039           -0.153
ICPS__DLPFC__:_:  0.101           -0.196          -0.038

Computing profile confidence intervals ...

In [38]:
label <- "peri_midlateral"
plot_label <- 'PERI'
model <- lmer(peri_rt ~ ICPS_early_MOTOR_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub),
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: peri_rt ~ ICPS_early_MOTOR_diff_collapsed * age_m * soc + sex +
    dp_inperson + (1 | sub)
   Data: tf_data

REML criterion at convergence: 1181.3

Scaled residuals:
    Min      1Q  Median      3Q     Max
-3.4106 -0.5572 -0.0146  0.5841  2.9674

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.05914  0.2432
 Residual             0.93866  0.9688
Number of obs: 406, groups:  sub, 227

Fixed effects:
                                             Estimate Std. Error         df
(Intercept)                                  0.013553   0.074477 210.107070
ICPS_early_MOTOR_diff_collapsed             -0.044827   0.052063 347.766792
age_m                                       -0.013115   0.052148 215.715116
soc1                                         0.113377   0.049047 207.537956
sex1                                         0.001365   0.051171 206.090270
dp_inperson1                                -0.012686   0.073768 207.618487
ICPS_early_MOTOR_diff_collapsed:age_m        0.016799   0.051647 380.223766
ICPS_early_MOTOR_diff_collapsed:soc1        -0.052513   0.050885 326.444862
age_m:soc1                                   0.070232   0.049584 214.690888
ICPS_early_MOTOR_diff_collapsed:age_m:soc1  -0.038203   0.050708 367.774163
                                           t value Pr(>|t|)
(Intercept)                                  0.182   0.8558
ICPS_early_MOTOR_diff_collapsed             -0.861   0.3898
age_m                                       -0.251   0.8017
soc1                                         2.312   0.0218 *
sex1                                         0.027   0.9787
dp_inperson1                                -0.172   0.8636
ICPS_early_MOTOR_diff_collapsed:age_m        0.325   0.7452
ICPS_early_MOTOR_diff_collapsed:soc1        -1.032   0.3028
age_m:soc1                                   1.416   0.1581
ICPS_early_MOTOR_diff_collapsed:age_m:soc1  -0.753   0.4517
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
                 (Intr) ICPS_r_MOTOR__ age_m  soc1   sex1   dp_np1
ICPS_r_MOTOR__    0.050
age_m             0.030 -0.157
soc1             -0.033 -0.049          0.028
sex1             -0.003  0.065          0.008  0.005
dp_inpersn1      -0.721 -0.045         -0.051  0.018 -0.018
ICPS_r_MOTOR__:_ -0.177 -0.190         -0.009  0.024 -0.055  0.092
ICPS__MOTOR__:1   0.011 -0.020          0.047  0.026  0.045 -0.059
age_m:soc1        0.023  0.044         -0.013 -0.010 -0.032 -0.003
ICPS__MOTOR__:_:  0.018 -0.033         -0.085 -0.166  0.032 -0.004
                 ICPS_r_MOTOR__:_ ICPS__MOTOR__:1 ag_m:1
ICPS_r_MOTOR__
age_m
soc1
sex1
dp_inpersn1
ICPS_r_MOTOR__:_
ICPS__MOTOR__:1  -0.041
age_m:soc1       -0.089           -0.165
ICPS__MOTOR__:_:  0.072           -0.171          -0.006

Computing profile confidence intervals ...

In [39]:
label <- "peri_posterolateral"
plot_label <- 'PERI'
model <- lmer(peri_rt ~ ICPS_early_OCC_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub),
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: peri_rt ~ ICPS_early_OCC_diff_collapsed * age_m * soc + sex +
    dp_inperson + (1 | sub)
   Data: tf_data

REML criterion at convergence: 1128.7

Scaled residuals:
    Min      1Q  Median      3Q     Max
-3.3481 -0.5497 -0.0028  0.5615  2.9882

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.08612  0.2935
 Residual             0.85320  0.9237
Number of obs: 396, groups:  sub, 221

Fixed effects:
                                          Estimate Std. Error        df t value
(Intercept)                                0.04466    0.07239 202.08298   0.617
ICPS_early_OCC_diff_collapsed             -0.01042    0.05074 360.91437  -0.205
age_m                                     -0.01460    0.05131 208.66086  -0.284
soc1                                       0.07498    0.04716 199.63549   1.590
sex1                                      -0.01590    0.05084 201.51847  -0.313
dp_inperson1                              -0.03008    0.07233 201.86938  -0.416
ICPS_early_OCC_diff_collapsed:age_m       -0.00263    0.04850 384.49040  -0.054
ICPS_early_OCC_diff_collapsed:soc1        -0.01447    0.04931 332.58795  -0.294
age_m:soc1                                 0.03862    0.04742 206.28909   0.814
ICPS_early_OCC_diff_collapsed:age_m:soc1   0.02357    0.04787 372.21731   0.492
                                         Pr(>|t|)
(Intercept)                                 0.538
ICPS_early_OCC_diff_collapsed               0.837
age_m                                       0.776
soc1                                        0.113
sex1                                        0.755
dp_inperson1                                0.678
ICPS_early_OCC_diff_collapsed:age_m         0.957
ICPS_early_OCC_diff_collapsed:soc1          0.769
age_m:soc1                                  0.416
ICPS_early_OCC_diff_collapsed:age_m:soc1    0.623

Correlation of Fixed Effects:
               (Intr) ICPS_r_OCC__ age_m  soc1   sex1   dp_np1 ICPS_r_OCC__:_
ICPS_r_OCC__   -0.004
age_m           0.036 -0.007
soc1           -0.024  0.001        0.032
sex1           -0.015  0.043        0.007  0.012
dp_inpersn1    -0.708  0.027       -0.052  0.002 -0.005
ICPS_r_OCC__:_  0.022 -0.030        0.021  0.136 -0.066 -0.045
ICPS__OCC__:1  -0.009 -0.038        0.133  0.024 -0.029  0.017  0.063
age_m:soc1      0.018  0.143       -0.029 -0.002  0.016  0.006  0.041
ICPS__OCC__:_:  0.070  0.065        0.047 -0.017  0.033  0.031 -0.109
               ICPS__OCC__:1 ag_m:1
ICPS_r_OCC__
age_m
soc1
sex1
dp_inpersn1
ICPS_r_OCC__:_
ICPS__OCC__:1
age_m:soc1     -0.008
ICPS__OCC__:_: -0.012         0.016

Computing profile confidence intervals ...

In [40]:
label <- "peri_all_three"
plot_label <- 'PERI'
model <- lmer(peri_rt ~ ICPS_early_OCC_diff_collapsed * age_m  * soc + ICPS_early_MOTOR_diff_collapsed * age_m * soc + ICPS_early_DLPFC_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub),
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Correlation matrix not shown by default, as p = 18 > 12.
Use print(obj, correlation=TRUE)  or
    vcov(obj)        if you need it

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula:
peri_rt ~ ICPS_early_OCC_diff_collapsed * age_m * soc + ICPS_early_MOTOR_diff_collapsed *
    age_m * soc + ICPS_early_DLPFC_diff_collapsed * age_m * soc +
    sex + dp_inperson + (1 | sub)
   Data: tf_data

REML criterion at convergence: 1088.6

Scaled residuals:
    Min      1Q  Median      3Q     Max
-3.3334 -0.5924 -0.0033  0.5408  2.9411

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.08003  0.2829
 Residual             0.87657  0.9363
Number of obs: 371, groups:  sub, 215

Fixed effects:
                                             Estimate Std. Error         df
(Intercept)                                 2.611e-02  7.820e-02  2.131e+02
ICPS_early_OCC_diff_collapsed               1.290e-02  5.498e-02  3.431e+02
age_m                                      -1.297e-03  5.505e-02  2.074e+02
soc1                                        9.307e-02  5.082e-02  1.971e+02
ICPS_early_MOTOR_diff_collapsed            -1.210e-01  6.493e-02  3.354e+02
ICPS_early_DLPFC_diff_collapsed             1.013e-01  6.186e-02  3.508e+02
sex1                                       -2.627e-02  5.323e-02  1.967e+02
dp_inperson1                                2.381e-03  7.697e-02  2.125e+02
ICPS_early_OCC_diff_collapsed:age_m         4.477e-03  5.208e-02  3.530e+02
ICPS_early_OCC_diff_collapsed:soc1          1.594e-02  5.401e-02  3.253e+02
age_m:soc1                                  3.896e-02  5.143e-02  2.026e+02
age_m:ICPS_early_MOTOR_diff_collapsed       2.039e-04  6.126e-02  3.433e+02
soc1:ICPS_early_MOTOR_diff_collapsed       -1.691e-02  6.303e-02  3.102e+02
age_m:ICPS_early_DLPFC_diff_collapsed       1.780e-02  5.808e-02  3.523e+02
soc1:ICPS_early_DLPFC_diff_collapsed       -4.927e-03  6.106e-02  3.407e+02
ICPS_early_OCC_diff_collapsed:age_m:soc1    4.862e-02  5.178e-02  3.489e+02
age_m:soc1:ICPS_early_MOTOR_diff_collapsed -6.883e-02  5.983e-02  3.279e+02
age_m:soc1:ICPS_early_DLPFC_diff_collapsed  5.600e-02  5.779e-02  3.484e+02
                                           t value Pr(>|t|)
(Intercept)                                  0.334   0.7388
ICPS_early_OCC_diff_collapsed                0.235   0.8146
age_m                                       -0.024   0.9812
soc1                                         1.831   0.0685 .
ICPS_early_MOTOR_diff_collapsed             -1.864   0.0632 .
ICPS_early_DLPFC_diff_collapsed              1.637   0.1025
sex1                                        -0.493   0.6222
dp_inperson1                                 0.031   0.9754
ICPS_early_OCC_diff_collapsed:age_m          0.086   0.9316
ICPS_early_OCC_diff_collapsed:soc1           0.295   0.7681
age_m:soc1                                   0.757   0.4497
age_m:ICPS_early_MOTOR_diff_collapsed        0.003   0.9973
soc1:ICPS_early_MOTOR_diff_collapsed        -0.268   0.7887
age_m:ICPS_early_DLPFC_diff_collapsed        0.306   0.7594
soc1:ICPS_early_DLPFC_diff_collapsed        -0.081   0.9357
ICPS_early_OCC_diff_collapsed:age_m:soc1     0.939   0.3484
age_m:soc1:ICPS_early_MOTOR_diff_collapsed  -1.150   0.2508
age_m:soc1:ICPS_early_DLPFC_diff_collapsed   0.969   0.3332
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Computing profile confidence intervals ...

## PES

In [46]:
label <- "pes_frontolateral"
plot_label <- 'PES'
model <- lmer(pes ~ ICPS_early_DLPFC_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub),
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula:
pes ~ ICPS_early_DLPFC_diff_collapsed * age_m * soc + sex + dp_inperson +
    (1 | sub)
   Data: tf_data

REML criterion at convergence: 1116.3

Scaled residuals:
     Min       1Q   Median       3Q      Max
-3.07475 -0.56359  0.02076  0.57474  2.61654

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.2676   0.5173
 Residual             0.6553   0.8095
Number of obs: 399, groups:  sub, 224

Fixed effects:
                                             Estimate Std. Error         df
(Intercept)                                -2.140e-02  7.960e-02  2.293e+02
ICPS_early_DLPFC_diff_collapsed            -8.071e-02  4.990e-02  3.882e+02
age_m                                       8.339e-02  5.450e-02  2.153e+02
soc1                                       -3.154e-02  4.186e-02  1.980e+02
sex1                                        2.361e-01  5.380e-02  2.081e+02
dp_inperson1                                4.909e-02  7.928e-02  2.281e+02
ICPS_early_DLPFC_diff_collapsed:age_m      -2.655e-02  4.846e-02  3.874e+02
ICPS_early_DLPFC_diff_collapsed:soc1        1.260e-03  4.719e-02  3.265e+02
age_m:soc1                                  1.082e-01  4.209e-02  2.005e+02
ICPS_early_DLPFC_diff_collapsed:age_m:soc1 -7.642e-04  4.639e-02  3.377e+02
                                           t value Pr(>|t|)
(Intercept)                                 -0.269   0.7883
ICPS_early_DLPFC_diff_collapsed             -1.617   0.1066
age_m                                        1.530   0.1275
soc1                                        -0.753   0.4521
sex1                                         4.387 1.82e-05 ***
dp_inperson1                                 0.619   0.5364
ICPS_early_DLPFC_diff_collapsed:age_m       -0.548   0.5841
ICPS_early_DLPFC_diff_collapsed:soc1         0.027   0.9787
age_m:soc1                                   2.572   0.0108 *
ICPS_early_DLPFC_diff_collapsed:age_m:soc1  -0.016   0.9869
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
                 (Intr) ICPS_r_DLPFC__ age_m  soc1   sex1   dp_np1
ICPS_r_DLPFC__    0.031
age_m             0.071 -0.120
soc1             -0.015  0.045         -0.001
sex1             -0.022 -0.036          0.010 -0.012
dp_inpersn1      -0.731 -0.035         -0.078  0.016 -0.016
ICPS_r_DLPFC__:_ -0.107 -0.148         -0.071 -0.027  0.027  0.023
ICPS__DLPFC__:1   0.060  0.148         -0.029  0.030 -0.014 -0.036
age_m:soc1        0.013 -0.032          0.011  0.025 -0.002 -0.015
ICPS__DLPFC__:_:  0.023 -0.032          0.038 -0.161  0.023 -0.055
                 ICPS_r_DLPFC__:_ ICPS__DLPFC__:1 ag_m:1
ICPS_r_DLPFC__
age_m
soc1
sex1
dp_inpersn1
ICPS_r_DLPFC__:_
ICPS__DLPFC__:1  -0.027
age_m:soc1        0.004           -0.145
ICPS__DLPFC__:_:  0.072           -0.197          -0.057

Computing profile confidence intervals ...

In [47]:
label <- "pes_midlateral"
plot_label <- 'PES'
model <- lmer(pes ~ ICPS_early_MOTOR_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub),
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula:
pes ~ ICPS_early_MOTOR_diff_collapsed * age_m * soc + sex + dp_inperson +
    (1 | sub)
   Data: tf_data

REML criterion at convergence: 1142.3

Scaled residuals:
     Min       1Q   Median       3Q      Max
-2.99023 -0.54866  0.05665  0.56788  3.04109

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.1796   0.4238
 Residual             0.7332   0.8562
Number of obs: 407, groups:  sub, 226

Fixed effects:
                                             Estimate Std. Error         df
(Intercept)                                 -0.059613   0.074934 219.877195
ICPS_early_MOTOR_diff_collapsed              0.036512   0.050574 373.963814
age_m                                        0.025630   0.052093 221.697835
soc1                                        -0.051484   0.043741 209.703941
sex1                                         0.233921   0.051566 213.948463
dp_inperson1                                 0.075153   0.074222 215.735640
ICPS_early_MOTOR_diff_collapsed:age_m       -0.005322   0.048873 392.357536
ICPS_early_MOTOR_diff_collapsed:soc1        -0.070988   0.046921 307.025029
age_m:soc1                                   0.120833   0.043908 213.917603
ICPS_early_MOTOR_diff_collapsed:age_m:soc1   0.070411   0.046420 346.043610
                                           t value Pr(>|t|)
(Intercept)                                 -0.796  0.42715
ICPS_early_MOTOR_diff_collapsed              0.722  0.47077
age_m                                        0.492  0.62320
soc1                                        -1.177  0.24052
sex1                                         4.536 9.54e-06 ***
dp_inperson1                                 1.013  0.31241
ICPS_early_MOTOR_diff_collapsed:age_m       -0.109  0.91334
ICPS_early_MOTOR_diff_collapsed:soc1        -1.513  0.13133
age_m:soc1                                   2.752  0.00643 **
ICPS_early_MOTOR_diff_collapsed:age_m:soc1   1.517  0.13022
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
                 (Intr) ICPS_r_MOTOR__ age_m  soc1   sex1   dp_np1
ICPS_r_MOTOR__    0.039
age_m             0.037 -0.163
soc1             -0.030 -0.052          0.036
sex1             -0.002  0.054          0.015 -0.003
dp_inpersn1      -0.720 -0.036         -0.054  0.019 -0.023
ICPS_r_MOTOR__:_ -0.165 -0.197          0.004  0.025 -0.061  0.076
ICPS__MOTOR__:1   0.002 -0.016          0.037  0.017  0.052 -0.042
age_m:soc1        0.029  0.043         -0.027 -0.001 -0.022 -0.003
ICPS__MOTOR__:_:  0.021 -0.027         -0.061 -0.181  0.029 -0.013
                 ICPS_r_MOTOR__:_ ICPS__MOTOR__:1 ag_m:1
ICPS_r_MOTOR__
age_m
soc1
sex1
dp_inpersn1
ICPS_r_MOTOR__:_
ICPS__MOTOR__:1  -0.030
age_m:soc1       -0.081           -0.184
ICPS__MOTOR__:_:  0.050           -0.152           0.013

Computing profile confidence intervals ...

In [48]:
label <- "pes_posterolateral"
plot_label <- 'PES'
model <- lmer(pes ~ ICPS_early_OCC_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub),
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula:
pes ~ ICPS_early_OCC_diff_collapsed * age_m * soc + sex + dp_inperson +
    (1 | sub)
   Data: tf_data

REML criterion at convergence: 1106.5

Scaled residuals:
     Min       1Q   Median       3Q      Max
-3.03988 -0.56122  0.03695  0.58383  2.59889

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.2191   0.4681
 Residual             0.6762   0.8223
Number of obs: 398, groups:  sub, 223

Fixed effects:
                                          Estimate Std. Error        df t value
(Intercept)                               -0.04212    0.07474 207.53236  -0.564
ICPS_early_OCC_diff_collapsed             -0.02870    0.04894 381.52798  -0.587
age_m                                      0.04788    0.05261 214.14821   0.910
soc1                                      -0.03626    0.04236 197.52635  -0.856
sex1                                       0.23861    0.05233 207.28357   4.560
dp_inperson1                               0.06571    0.07468 206.95421   0.880
ICPS_early_OCC_diff_collapsed:age_m       -0.06908    0.04625 387.03329  -1.493
ICPS_early_OCC_diff_collapsed:soc1        -0.03110    0.04541 308.65645  -0.685
age_m:soc1                                 0.10025    0.04252 202.87076   2.358
ICPS_early_OCC_diff_collapsed:age_m:soc1   0.07901    0.04486 354.80982   1.761
                                         Pr(>|t|)
(Intercept)                                0.5737
ICPS_early_OCC_diff_collapsed              0.5579
age_m                                      0.3638
soc1                                       0.3930
sex1                                     8.76e-06 ***
dp_inperson1                               0.3799
ICPS_early_OCC_diff_collapsed:age_m        0.1361
ICPS_early_OCC_diff_collapsed:soc1         0.4940
age_m:soc1                                 0.0193 *
ICPS_early_OCC_diff_collapsed:age_m:soc1   0.0790 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
               (Intr) ICPS_r_OCC__ age_m  soc1   sex1   dp_np1 ICPS_r_OCC__:_
ICPS_r_OCC__   -0.004
age_m           0.042  0.003
soc1           -0.020  0.007        0.037
sex1           -0.010  0.041        0.013  0.008
dp_inpersn1    -0.709  0.018       -0.056  0.003 -0.012
ICPS_r_OCC__:_  0.023 -0.046        0.017  0.149 -0.049 -0.039
ICPS__OCC__:1  -0.003 -0.019        0.132  0.017 -0.031  0.015  0.088
age_m:soc1      0.023  0.158       -0.033  0.000  0.023  0.003  0.027
ICPS__OCC__:_:  0.068  0.094        0.042 -0.018  0.030  0.034 -0.105
               ICPS__OCC__:1 ag_m:1
ICPS_r_OCC__
age_m
soc1
sex1
dp_inpersn1
ICPS_r_OCC__:_
ICPS__OCC__:1
age_m:soc1     -0.007
ICPS__OCC__:_: -0.008         0.011

Computing profile confidence intervals ...

In [49]:
label <- "pes_all_three"
plot_label <- 'PES'
model <- lmer(pes ~ ICPS_early_OCC_diff_collapsed * age_m  * soc + ICPS_early_MOTOR_diff_collapsed * age_m * soc + ICPS_early_DLPFC_diff_collapsed * age_m  * soc + sex + dp_inperson + (1 | sub),
              data = tf_data)
summary(model)

lmer_export_apa(model = model, path = sprintf("%s/%s.docx", table_output_path, label))

Correlation matrix not shown by default, as p = 18 > 12.
Use print(obj, correlation=TRUE)  or
    vcov(obj)        if you need it

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula:
pes ~ ICPS_early_OCC_diff_collapsed * age_m * soc + ICPS_early_MOTOR_diff_collapsed *
    age_m * soc + ICPS_early_DLPFC_diff_collapsed * age_m * soc +
    sex + dp_inperson + (1 | sub)
   Data: tf_data

REML criterion at convergence: 1060.8

Scaled residuals:
     Min       1Q   Median       3Q      Max
-2.79992 -0.56302  0.03411  0.57897  2.67977

Random effects:
 Groups   Name        Variance Std.Dev.
 sub      (Intercept) 0.2336   0.4833
 Residual             0.6668   0.8166
Number of obs: 372, groups:  sub, 217

Fixed effects:
                                            Estimate Std. Error        df
(Intercept)                                 -0.01850    0.07984 212.63271
ICPS_early_OCC_diff_collapsed               -0.03491    0.05295 353.80655
age_m                                        0.04917    0.05615 207.74398
soc1                                        -0.04070    0.04500 184.90225
ICPS_early_MOTOR_diff_collapsed              0.14050    0.06291 349.74541
ICPS_early_DLPFC_diff_collapsed             -0.12945    0.05812 352.98314
sex1                                         0.23774    0.05477 197.37482
dp_inperson1                                 0.05576    0.07867 210.38696
ICPS_early_OCC_diff_collapsed:age_m         -0.08365    0.04891 348.85600
ICPS_early_OCC_diff_collapsed:soc1          -0.02789    0.05015 298.84926
age_m:soc1                                   0.12578    0.04544 188.56899
age_m:ICPS_early_MOTOR_diff_collapsed        0.02310    0.05906 351.37211
soc1:ICPS_early_MOTOR_diff_collapsed        -0.09765    0.05789 275.86526
age_m:ICPS_early_DLPFC_diff_collapsed       -0.03306    0.05426 353.71313
soc1:ICPS_early_DLPFC_diff_collapsed         0.02717    0.05606 320.35401
ICPS_early_OCC_diff_collapsed:age_m:soc1     0.04580    0.04823 334.92207
age_m:soc1:ICPS_early_MOTOR_diff_collapsed   0.04741    0.05511 297.41652
age_m:soc1:ICPS_early_DLPFC_diff_collapsed  -0.02030    0.05320 338.99384
                                           t value Pr(>|t|)
(Intercept)                                 -0.232   0.8170
ICPS_early_OCC_diff_collapsed               -0.659   0.5101
age_m                                        0.876   0.3822
soc1                                        -0.904   0.3669
ICPS_early_MOTOR_diff_collapsed              2.233   0.0262 *
ICPS_early_DLPFC_diff_collapsed             -2.227   0.0266 *
sex1                                         4.341 2.27e-05 ***
dp_inperson1                                 0.709   0.4792
ICPS_early_OCC_diff_collapsed:age_m         -1.710   0.0881 .
ICPS_early_OCC_diff_collapsed:soc1          -0.556   0.5785
age_m:soc1                                   2.768   0.0062 **
age_m:ICPS_early_MOTOR_diff_collapsed        0.391   0.6959
soc1:ICPS_early_MOTOR_diff_collapsed        -1.687   0.0928 .
age_m:ICPS_early_DLPFC_diff_collapsed       -0.609   0.5427
soc1:ICPS_early_DLPFC_diff_collapsed         0.485   0.6282
ICPS_early_OCC_diff_collapsed:age_m:soc1     0.950   0.3430
age_m:soc1:ICPS_early_MOTOR_diff_collapsed   0.860   0.3903
age_m:soc1:ICPS_early_DLPFC_diff_collapsed  -0.382   0.7030
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Computing profile confidence intervals ...